### ISSUE TITLE
onion/carrots stored in main area doesn't show in pda overview

### ISSUE THREAD

**Issue by cill2003** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#100]
i've put a great amount in the central storage area in the centre of the map, it still says 0 in the pda overview ...

**Comment by BROADACRES16xFS17MAP** [comment]
Please see manual. The storage you are tipping into is a temp storage for traims and trailers to collect from and will show the amounts in the menu when you go to refill. For long term storage please dump in the one just a little further up and to the left in the centre area and it will then show on pda. Adjacent to the vegetable storage sheds.

**Comment by cill2003** [comment]
Then i'm guessing i'm playing a different map then you guys are .... I'm dumping in the sheds, clearly stated in manual carrot storage, onion storage etc .... And this doesn't show in de pda overview .... 


Van: "BROADACRES16xFS17MAP" <notifications@github.com> 
Aan: "BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map" <Broad-Acres-16x-Australian-Map@noreply.github.com> 
Cc: "zwimpie" <zwimpie@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Woensdag 27 december 2017 19:18:49 
Onderwerp: Re: [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map] onion/carrots stored in main area doesn't show in pda overview (#100) 



Please see manual. The storage you are tipping into is a temp storage for trai s and trailers to collect from and will show the amounts in the menu when you go to refill. For long term storage please dump in the one just a little further up and to the left in the centre area. Adjacent to the vegetable storage sheds.

**Comment by BROADACRES16xFS17MAP** [comment]
Ah you didnt say it was vegetables.  V2 has digital displays added. These wont show in pda as there are three lots of them.

**Comment by cill2003** [comment]
ok tyvm 



Van: "BROADACRES16xFS17MAP" <notifications@github.com> 
Aan: "BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map" <Broad-Acres-16x-Australian-Map@noreply.github.com> 
Cc: "zwimpie" <zwimpie@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Woensdag 27 december 2017 23:31:52 
Onderwerp: Re: [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map] onion/carrots stored in main area doesn't show in pda overview (#100) 



Ah you didnt say it was vegetables. V2 has digital displays added. These wont show in pda as there are three lots of them.
