### ISSUE TITLE
sell pallets/compost  ELDERS

### ISSUE THREAD

**Issue by cill2003** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#101]
According to pda overview you could sell empty pallets and compost at Elders.  Couldn't find anywhere to unload/sell at this place .....
do not mistake with elders wool !!

**Comment by BROADACRES16xFS17MAP** [comment]
Go to the rear of the elders building and trigger comes out from sliding door.

**Comment by cill2003** [comment]
Sliding doors???? i don't even see sliding doors ... The only thing i see are 3 concrete mixers next to each other .... 



Van: "BROADACRES16xFS17MAP" <notifications@github.com> 
Aan: "BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map" <Broad-Acres-16x-Australian-Map@noreply.github.com> 
Cc: "zwimpie" <zwimpie@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Woensdag 27 december 2017 19:49:00 
Onderwerp: Re: [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map] sell pallets/compost ELDERS (#101) 



Go to the rear of the elders building and trigger comes out from sliding door.

**Comment by BROADACRES16xFS17MAP** [comment]
At the rear of elders there is a roller door. The trigger is in front of that. If ever in doubt were a trigger is press f5 and it will show you.

**Comment by cill2003** [comment]
Hi, f5 doesn't do anything ..... 

attached a printscreen of the Elders building ... 




Van: "BROADACRES16xFS17MAP" <notifications@github.com> 
Aan: "BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map" <Broad-Acres-16x-Australian-Map@noreply.github.com> 
Cc: "zwimpie" <zwimpie@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Woensdag 27 december 2017 23:50:26 
Onderwerp: Re: [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map] sell pallets/compost ELDERS (#101) 



At the rear of elders there is a roller door. The trigger is in front of that. If ever in doubt were a trigger is press f5 and it will show you.

**Comment by BROADACRES16xFS17MAP** [comment]
I couldn't see your upload but see this one

![fsscreen_2017_12_28_20_05_05](https://user-images.githubusercontent.com/7673205/34406740-87396fd6-ec0a-11e7-8eaa-027e7e4da5fe.png)
