### ISSUE TITLE
from the south east corner of field 13,diagonaly in line with the North East corner of field 9.Courseplay doesnt recognise the corner of field 13.so as you drive the headland in courseplay it want to drive through the fence. 

### ISSUE THREAD

**Issue by SCRUFFYSCOT** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#102]

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks for the input SCRUFFSCOT. Have you got a picture with the markers activated? (just drag and drop into your reply box). Ive tested on V2 and appears okay so may have been a V1 issue. Have you got v1.1?

**Comment by BROADACRES16xFS17MAP** [comment]
Is this the corner?

![fsscreen_2018_01_03_07_41_03](https://user-images.githubusercontent.com/7673205/34500190-9a2509a4-f059-11e7-81cb-2da6a5548213.png)

**Comment by SCRUFFYSCOT** [comment]
![screenshot 6](https://user-images.githubusercontent.com/35038195/34517595-8eaf4890-f073-11e7-8f1e-5ba8a128cb94.png)
![screenshot 7](https://user-images.githubusercontent.com/35038195/34517700-fe050cde-f073-11e7-9f93-f758df5539c4.png)
![screenshot 8](https://user-images.githubusercontent.com/35038195/34517733-2f84ef54-f074-11e7-83f0-d38d5cbba5fa.png)
AS requested thankyou :)

**Comment by SCRUFFYSCOT** [comment]
sorry ive got version 1.0 haven't managed how to figure out how to download the upgrade :(

**Comment by BROADACRES16xFS17MAP** [comment]
What courseplay settings have you got?
 Last.picture has field 10 not 13.

**Comment by BROADACRES16xFS17MAP** [comment]
1.1 links are on our facebook page under pinned post.

**Comment by SCRUFFYSCOT** [comment]
I'm sure the courseplay is up to date, yea says field 10 slip of the mouse.
Tried downloading g 1.1and its wiped 1.0 off my laptop

**Comment by SCRUFFYSCOT** [comment]
Well I tried downloading the 1.1 map to know success.
Even deleted 1.0 off completely and still didn't work.
Tried merging both files still nothing, so have reverted back to 1.0

**Comment by BROADACRES16xFS17MAP** [comment]
Download v1.1 from here. Unzip the files and place the Broad_Acres.zip into the mods folder and good to go.
