### ISSUE TITLE
Can't install map collision version 

### ISSUE THREAD

**Issue by OleJonesy** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#104]
Just downloaded map from modhub which was the collision version unzipped everything but when trying to install the map it's not showing up I looked at the moddesc and the icon file is a png but in the folder it's a dds with no image

**Comment by BROADACRES16xFS17MAP** [comment]
Did you keep Broad Acres.zip zipped up in your mods folder? Show me a pic of your mods folder with the new zips in as well as attach your log.txt thanks

**Comment by BROADACRES16xFS17MAP** [comment]
I will close this issue pending reply from user.

**Comment by OleJonesy** [comment]
It does show up in game when you drop it straight to the mods folder it's just a problem if you're using a mods manager

**Comment by BROADACRES16xFS17MAP** [comment]
So you have it working?

**Comment by OleJonesy** [comment]
Yes it's working
