### ISSUE TITLE
Can't copy toll package

### ISSUE THREAD

**Issue by gwilson451** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#105]
![error](https://user-images.githubusercontent.com/36105718/35767811-bbc936e4-08ea-11e8-9ff1-87a7298a2d83.jpg)
 ANY ADVICE PLEASE

**Comment by BROADACRES16xFS17MAP** [comment]
Hi, have you unzipped the package before trying to copy them? Little more information please.

**Comment by gwilson451** [comment]
I unzipped the toll package and tried to copy each one into my mods folder and it comes up with the error message.

**Comment by BROADACRES16xFS17MAP** [comment]
Does the map work okay, maybe the d/l wasn't completed successfully?

**Comment by gwilson451** [comment]
Yes the map is fine, I will delete the map and download it again and see if it works

**Comment by BROADACRES16xFS17MAP** [comment]
No need I will give you a link were you can d/l the toll package. saves you downloading the whole thing again standby...

**Comment by BROADACRES16xFS17MAP** [comment]
Try this one and report back thanks

https://mega.nz/#!YfIXjATK!bRheZiZ5ZxT9p53byeG3MqSHKksqjahqrnsvj8YphOU

**Comment by gwilson451** [comment]
Ok I will try it

**Comment by gwilson451** [comment]
Thank you, it is working now

**Comment by BROADACRES16xFS17MAP** [comment]
great to hear.
