### ISSUE TITLE
Field 19 has an island that is not marked

### ISSUE THREAD

**Issue by Sav19** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#110]
In field 19 there is an island that is not marked so courseplay can't pick it up.

![20180205223442_1](https://user-images.githubusercontent.com/33447815/35804799-f8e3fb1e-0ac4-11e8-8e39-7ddef4e89b2f.jpg)

![inked20180205223643_1_li](https://user-images.githubusercontent.com/33447815/35804889-5e6e38be-0ac5-11e8-853a-b0ad152a271b.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks we will take a look.

**Comment by BROADACRES16xFS17MAP** [comment]
Okay managed to test this and I am not having any issues as show in photo below. Maybe rerun courseplay  with settings I have below. Thanks

![fsscreen_2018_02_08_05_44_12](https://user-images.githubusercontent.com/7673205/35936454-39e3514e-0c93-11e8-9b34-1ceae277d3d6.png)
