### ISSUE TITLE
error code after downloading

### ISSUE THREAD

**Issue by bigcountry1089** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#113]
![image](https://user-images.githubusercontent.com/33584780/35834859-94883708-0aa5-11e8-8407-4f944b1e5d69.png)
I downloaded v2 and try to move from download folder to mod folder and get error code 0x80004005 which after checking it out is a windows xp error and I'm running windows 10 screen shot below

![untitled](https://user-images.githubusercontent.com/33584780/35834947-fc812180-0aa5-11e8-86fa-057a5579416d.jpg)

**Comment by bigcountry1089** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1697255/log.txt)
this goes with issue goofed the first

**Comment by BROADACRES16xFS17MAP** [comment]
#105 please see this one for new download on toll package
