### ISSUE TITLE
Animals disappearing of train and glitched

### ISSUE THREAD

**Issue by Ranky1984** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#114]
Hi All, i loaded sheep on to train, now the rear animal carriage has glitched, its showing that there is 0% sheep but i cant unload nor load any animal into rear carriage, also when i put 25 pigs in front carriage they disappeared about half way to drop off point.

**Comment by BROADACRES16xFS17MAP** [comment]
Please try again without any mods (except for Broad Acres mods) and report back.

**Comment by Ranky1984** [comment]
just tried again with a new game only had the broad acres mods active,
will attach screen shot when buying from stock yards.
![20180207152156_1](https://user-images.githubusercontent.com/32923034/35898469-02538dd4-0c1b-11e8-93a0-ff6b38a3789b.jpg)
![20180207152216_1](https://user-images.githubusercontent.com/32923034/35898474-078fd366-0c1b-11e8-888c-bf5c983b2899.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Sorry im confused is it the train or the trailer? If you can let us know the full details of what you are doing and whats going wrong we will test. Cheers

**Comment by Ranky1984** [comment]
Sorry guys i didnt realise when it first happened but the way it looks now that the glitch occurs when buying from stockyards this was the second load ill tried to buy, i got to 47 sheep and then it went to 47.*****, and then i cancelled the sale and went back into purchase again and then it showed picture 1

**Comment by BROADACRES16xFS17MAP** [comment]
okay so if I am reading this right, your loading sheep onto the trailer on second run and it shows none in the trailer and none on the pda screen?

**Comment by Ranky1984** [comment]
yeah but that 0.0082077******** wont go away still trying to load a partial sheep and if i load that on train it wont unload

**Comment by BROADACRES16xFS17MAP** [comment]
Can you attach your log.txt please

**Comment by BROADACRES16xFS17MAP** [comment]
Okay we have tested. This is what we did:

- Load sheep, full trailer, from markets to train yard and unloaded.

- Repeated same for a second load (total 96 sheep)

- Loaded front and back train carriage (total of 96 loaded into carriages)

- Took trailer back to market and could reload another lot.

We did not have any issues and did not get that red counter issue. I'm leaning towards a mod issue (take all mods out of the mods folder and try again. If you have done something different to above please upload what you did like I have done so we can try and replicate it. I have attached pictures to show.

**Comment by BROADACRES16xFS17MAP** [comment]
![fsscreen_2018_02_07_16_36_05](https://user-images.githubusercontent.com/7673205/35901466-9db9f35c-0c26-11e8-82af-a4933aec1686.png)
![fsscreen_2018_02_07_16_36_58](https://user-images.githubusercontent.com/7673205/35901467-9defdf8a-0c26-11e8-9098-46afc3c4576d.png)
![fsscreen_2018_02_07_16_31_42](https://user-images.githubusercontent.com/7673205/35901468-9ec77238-0c26-11e8-8a28-97bfb43017ab.png)
![fsscreen_2018_02_07_16_31_50](https://user-images.githubusercontent.com/7673205/35901469-9f038e76-0c26-11e8-9013-0b7446704118.png)

**Comment by Ranky1984** [comment]
hmm... im just gunna delete all the mods and start again... sorry to have bothered you. never had the issue on V1, ill put log.txt up as well, got me beat whats causing it, sorry again, by the way love the map got 60+ hours on V2 keep up the good work
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1701982/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
all good mate thats what this forum is for to help. If you have done the same process I have then I can only put it down to a mod conflict. p.s. your game is still loading all your mods with one without a moddesc so could be your issue. Remove all your mods and place them in a separate folder then try again. I'll close the issue but let us know how you go.

**Comment by Ranky1984** [comment]
hi ive done testing at appears to the road train pack mod causing the issue with the animals

**Comment by BROADACRES16xFS17MAP** [comment]
Ah yes the trailer that is included in the toll pack is the only trailer you can use.

**Comment by Ranky1984** [comment]
yeah had the R/T pack active but wasnt using it nor had i bought the trailer but still caused the glitch have every other mod active again except R/T and no problems

**Comment by BROADACRES16xFS17MAP** [comment]
Glad you got it fixed
