### ISSUE TITLE
Power Lines not showing up as Islands in CP

### ISSUE THREAD

**Issue by EpicPopsicle** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#115]
G'day

For some reason none of the power lines are showing up as islands on Course Play. So I cannot select the mode for them to go around the power polls. I have tried running it only the Broad Acres mod set, Course Play and a money cheat mod and still doesn't work (I have also deleted all other maps from my map folder).

https://imgur.com/LlLUiCO

(For some reason I couldn't upload the image directly)

**Comment by BROADACRES16xFS17MAP** [comment]
Hi, make sure you have CP generator page setup like this for it to work.

![fsscreen_2018_02_08_05_34_49](https://user-images.githubusercontent.com/7673205/35936059-17d1fa5c-0c92-11e8-86fb-23f548239029.png)

**Comment by EpicPopsicle** [comment]
Sorry I didn't realise it had to be set to current vehicle position for it to work. My bad. It's working now.

Ps Cheers for the awesome South Australian map, love play in my home state!

**Comment by BROADACRES16xFS17MAP** [comment]
Nice mate, all good
