### ISSUE TITLE
map does not start

### ISSUE THREAD

**Issue by typherian** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#118]
well as it says above map fails to start. Error message "bad allocation out of memory" i am using only the mods in the original rar downloaded from original facebook page
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1720296/log.txt)
![untitled](https://user-images.githubusercontent.com/36447650/36155889-3e0a5e4e-10de-11e8-8e63-de12e45f30a8.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Unfortunately your pc specs are very small and it cant run this map. It looks like you are inly running our mods and it still cant run it.

**Comment by BROADACRES16xFS17MAP** [comment]
Try turning your fs17 graphic options right down. You jave then on custom high at this time. That may help.

**Comment by Nervond** [comment]
i5-7500 gtx 1060 6 gb 16 gb ram 256 ssd not enough?

**Comment by Nervond** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1723642/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Should.be okay. Try.removing all mods.and.just try map. Further.try.google with.this.error.as plenty of topics on it. Its.not a map issue.

**Comment by Nervond** [comment]
okey. i try only with map. not work. thx the help

**Comment by Nervond** [comment]
ahahahhh im computer genius:D:D:D:D
I start game x64 and WORK
x86 not work

**Comment by BROADACRES16xFS17MAP** [comment]
Haha well done ill let the other fella know a fix. Well done.
