### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nervond** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#119]
Hi! Unfortunately I know little about English. When the map is load i get crash.Out of memory bad allocation
pleas help me
![nevtelen](https://user-images.githubusercontent.com/36474325/36200329-9f65b9d8-117c-11e8-9130-af96d4e02548.png)

**Comment by BROADACRES16xFS17MAP** [comment]
#118

**Comment by Nervond** [comment]
i5-7500 gtx 1060 6 gb 16 gb ram 256 ssd not enough?

**Comment by Nervond** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1723656/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Please see link #118 above for a fix thanks.
