### ISSUE TITLE
broadacres v2 No Sound

### ISSUE THREAD

**Issue by SCRUFFYSCOT** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#120]
hi ive downlaoded v2 and im not getting any sound ?? Any suggestions,all other applications are sounding ok

**Comment by BROADACRES16xFS17MAP** [comment]
Hi no idea on that one. So you cant hear kookaburras when you first open the map? It's not the map as sound is working fine on others. I would suggest try different setting in your game.
