### ISSUE TITLE
Courseplay loading problem

### ISSUE THREAD

**Issue by farmwrangler** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#122]
Just wanted to put this out there in case anyone has this problem. I finally got some time to spend with v2 and want to do a video series on it. With just the map and the toll mods installed, the game loaded fine. Then I copied a hundred of my favorite mods in there, and it wouldn't load. then remembered that groundmodification doesn't work with 16x, removed it and still no load. Looked in the log and noticed it would hang with courseplay trying to read courseManager.xml. Found it in a folder called CoursePlay_Courses in the savegames folder. In it a subfolder called Broad_Acres.SampleModMap. Deleted all the files in it, and the map loaded fine. The files in it were left over from v1 and apparently it didn't like what it found. Don't know if it's possible to give v2 a different name other than Broad_Acres.SampleModMap or not, but it would probably solve this problem. Then courseplay wouldn't look for courseManager.xml in the v1 folder, but create a new folder with the new name.

If not, it's another fix to add to the fixit bank. :lol

**Comment by BROADACRES16xFS17MAP** [comment]
Not a map issue so not need to change the name. What I believe you have got is saved courseplay routes from v1. They wont work in v2 as everything has changed. Remove that folder and have courseplay start another. Make sure you dont save fields as they are gb in size so map will hang.

**Comment by farmwrangler** [comment]
:LOL you've just repeated back to me exactly what I said and did. I posted this so someone else who can't load your map may be able to solve the problem. Never said it was a map issue.
