### ISSUE TITLE
Product unloading

### ISSUE THREAD

**Issue by bcuda383** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#125]
I can load the toll curtain trailer just fine, but i cannot unload it at any of the business locations.  I used the supplied manual to find the correct drop off points. Mcdonalds, KFC, etc.  I can unload the toll diesel tanker at the fuel station.

**Comment by BROADACRES16xFS17MAP** [comment]
Working ok this end. Are you getting the unload trigger activating? Show me a pic of which one you are trying please.

**Comment by bcuda383** [comment]
![20180221072407_1](https://user-images.githubusercontent.com/36684795/36480021-c441353c-16d8-11e8-962d-0da9d9088982.jpg)
Bread at McDonalds

**Comment by BROADACRES16xFS17MAP** [comment]
Reverse in. Trigger is at the back.

**Comment by bcuda383** [comment]
ok got that one . where is the trigger at kfc?

**Comment by BROADACRES16xFS17MAP** [comment]
Please see the manual its all in there.
