### ISSUE TITLE
Bunker clamps not properly mapped (small bunkers)

### ISSUE THREAD

**Issue by blipadouzi** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#129]
When using the 20 small bunkers at the BGA, the chaff/silage spills out and is not covered by the tarp properly.  As a result, when dumping chaff into them, it spreads outside the bunker and dumps everywhere.

**Comment by BROADACRES16xFS17MAP** [comment]
is this in SP or MP? Also picture please?

**Comment by blipadouzi** [comment]
MP, on a dedicated server
