### ISSUE TITLE
compostmaker

### ISSUE THREAD

**Issue by Chalako** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#137]
Hi, i can't load fuel in the compostmaker.Not with the Toll trailer and not with the tanker from the road train pack.Can somebody help me?  Thank you.

**Comment by BROADACRES16xFS17MAP** [comment]
Please see the manual as it explains this in detail. You need to use the specific trailer for fuel.

**Comment by Chalako** [comment]
Thank you, i noticed it after a second look.I did'nt putt that Shell fuel
trailer in my mods folder.

Op zo 13 jan. 2019 om 23:01 schreef BROADACRES16xFS17MAP <
notifications@github.com>:
