### ISSUE TITLE
Pedido de ajuda/ edição 

### ISSUE THREAD

**Issue by DouglasDDR** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#140]
Gostaria de saber se teria como adicionar mais culturas ao mapa ?
Caso possam me enviar um tutorial como adicionar eu tento colocar no mapa. ( caso isso seja feito e para uso próprio)
Exemplo: Peanut , Mustard , Sorgum , Sadangrass , Rice.

**Comment by BROADACRES16xFS17MAP** [comment]
English please.

**Comment by DouglasDDR** [comment]
I wonder if you could add more cultures to the map?
If you allow me to send a tutorial how to add I try to put it on the map. (if this is done and for own use)
Example: Peanut, Mustard, Sorgum, Sadangrass, Rice.

**Comment by BROADACRES16xFS17MAP** [comment]
Australia doesnt really produce those items therefore will not be added to the map.
