### ISSUE TITLE
Use a Thor head mover on a front end loader to fix the small gate opening issue.

### ISSUE THREAD

**Issue by slowboat** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#16]
What I have done to fix the gates being too small is to use a Thor head mover on a front end loader so you can lift the header above the gate and then put the header in the field.

**Comment by slowboat** [comment]
Make sure you have a counter weight on the loader so you won't tip over.

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks slowboat. As discussed headers wont fit through gates and same in real life. I would suggest using the designated trailers you can buy in FS17 to tow them into field then connect.
