### ISSUE TITLE
Manual error

### ISSUE THREAD

**Issue by Bundy-Bear** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#18]
At the storage silo near field 17 the seed trigger is the one furthest from the liquid fertiliser

**Comment by BROADACRES16xFS17MAP** [comment]
Sorry mate not quite sure what you mean
 Maybe a pic?

**Comment by Bundy-Bear** [comment]
When you compare the manual (page 29) Seeds are in the middle, at field 17 Seeds are on the end, (gave up trying to fill seed from the centre at main silo, so went to field 17
![20171023110806_1](https://user-images.githubusercontent.com/32672100/31867937-5a3a90f6-b7e3-11e7-8609-b8616ac89ed8.jpg)

**Comment by Bundy-Bear** [comment]
Now I'm confused, the JD DB90 (mod) fills up as per above picture near field 17, however won't fill at the main silo. An in game sower (in this case the Horsch Maestro) refills at the main silo as per page 29 in the manual.

**Comment by BROADACRES16xFS17MAP** [comment]
I havent got the manual with me but are you buying seed or making it?

**Comment by Bundy-Bear** [comment]
I was trying to buy the seed.

**Comment by Bundy-Bear** [comment]
As the in game sower works as described in the manual, this now a non issue. Just be aware that the temporary silo's may be swapped around on the buy seed/fertiliser silo's

**Comment by BROADACRES16xFS17MAP** [comment]
I will update the manual to show all points in each area.
