### ISSUE TITLE
Equipment not for sale.

### ISSUE THREAD

**Issue by DrewDundee** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#20]
Moving someone else's post from the FB page.
Not sure if an issue or not.
Some of the machinery available on initial start-up, can not be sold (The forestry equipment, and the tractor on the eastern side of the map). Is this because it is 'leased' or because it just isn't yours to sell (the 'Old Boy' needs at least one tractor to run his cattle/sheep etc.)?

**Comment by Bundy-Bear** [comment]
You will find, that equipment is leased.

**Comment by BROADACRES16xFS17MAP** [comment]
Correct those vehicle are leased so need to send them back in order to get rid of them.
