### ISSUE TITLE
Unable to get CP to work.

### ISSUE THREAD

**Issue by Moonsorrow** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#21]
Hi, I'm having an issue with CP and that it won't bother to work for me.
I've watched a tutorial and done everything like it said, and yet nothing happens for me.
It's the same with all fields when I try to set it up.
This is the video I've been watching, and just like it's said and shown I have done.
https://www.youtube.com/watch?v=XSWnBi2jhJs

[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1408307/log.txt)

![fsscreen_2017_10_21_15_06_18](https://user-images.githubusercontent.com/32981822/31905606-08b5ae36-b82f-11e7-9750-074010596426.png)
![fsscreen_2017_10_23_19_55_26](https://user-images.githubusercontent.com/32981822/31905607-08e1e118-b82f-11e7-85db-3df28e845e6e.png)
![fsscreen_2017_10_23_19_55_37](https://user-images.githubusercontent.com/32981822/31905608-08ffbae4-b82f-11e7-8022-29cb0dfb8c53.png)
![fsscreen_2017_10_23_19_56_07](https://user-images.githubusercontent.com/32981822/31905609-091fdfd6-b82f-11e7-82a6-418ba84bf36b.png)
![fsscreen_2017_10_23_19_56_30](https://user-images.githubusercontent.com/32981822/31905610-093cd0d2-b82f-11e7-8184-0a8120f74f54.png)
![fsscreen_2017_10_23_19_57_52](https://user-images.githubusercontent.com/32981822/31905611-095bdbbc-b82f-11e7-8a9e-13f9a6347922.png)
![fsscreen_2017_10_23_20_01_49](https://user-images.githubusercontent.com/32981822/31905612-097d72c2-b82f-11e7-883c-898c5de4ce91.png)
![fsscreen_2017_10_23_20_04_08](https://user-images.githubusercontent.com/32981822/31905613-09a0ca38-b82f-11e7-9d3a-90d3b6ad1952.png)
![fsscreen_2017_10_23_20_04_18](https://user-images.githubusercontent.com/32981822/31905614-09bb8f94-b82f-11e7-988a-6ec0482026e2.png)

**Comment by BROADACRES16xFS17MAP** [comment]
Looking at the first picture have you redownloaded the map? There was a bug fix that was uploaded on the first day.

**Comment by Bundy-Bear** [comment]
Some suggestions, update your courseplay (I'm now running 5.02.00013) however your version should work.
How I do it.
On picture 1, ignore Calculate current fields edge path, and field edge path number
On picture 5, (course preparation)
Field edge path - select the field that you are in
Starting location - select which corner you wish to start
Starting direction - select which direction you wish to go
Return to start point  - I ignore
Headland - On Broad Acres I select 3
Then generate course.
Then On Courseplay control
Start course at  - select first waypoint
then select drive course
![cp](https://user-images.githubusercontent.com/32672100/31919993-c6766c62-b8b1-11e7-960d-ca479064284e.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Will close for now pending response from MoonSorrow

**Comment by Moonsorrow** [comment]
Hi again, well that worked. But for some reason 2 of the tractors keep doing headlands even though I haven't chosen them to do so. 
I have tried resetting them, but they just keepdoing headlands yet again. Only 1 of the 3 tractors drives around the field. Any idea on as why this happens? 

    Den tisdag, 24 oktober 2017 8:57 skrev BROADACRES16xFS17MAP <notifications@github.com>:
 

 Will close for now pending response from MoonSorrow—

**Comment by BROADACRES16xFS17MAP** [comment]
We will need a video mate to understand what you're doing. It would be an error when using CP rather than the map but happy to help but hard to understand it without visuals
