### ISSUE TITLE
Glitchy intersection 

### ISSUE THREAD

**Issue by FrmrJon** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#24]
The intersection between Field 22 and the bank has a glitch. When I look at it, it flashes.

**Comment by BROADACRES16xFS17MAP** [comment]
Yeah Giants in there wisdom doesn't allow overlay. With roads that need to be like that there is not much we can do until a Giants fix comes along. I'll look at another way to change that intersections but not a huge priority at the moment.

**Comment by BROADACRES16xFS17MAP** [comment]
Fixed
