### ISSUE TITLE
Cannot unload in sugarbeet storage area 

### ISSUE THREAD

**Issue by Scoot3826** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#26]
Dont knw if we can still post issues her but just thought i would give it a try to help you guys out. I unloaded one load in the sugarbeet storage at the middle of the map. The animation filled up the area and cannot reach the trigger anymore to unload.

**Comment by spectrum69** [comment]
you use ,what's mod please  and 1 picture = 1000 word

**Comment by BROADACRES16xFS17MAP** [comment]
This has been fixed in latest version
