### ISSUE TITLE
Silos at the central farm

### ISSUE THREAD

**Issue by DanielBeard83** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#27]
The silos at the central farm glow in the dark. The town is very bad on frame rates too. Cool map though. I am Aussie, born and bred, so I'm loving it.

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks Daniel, if your PC is smaller it will take a hit in the town. Due to the amount of factories etc in the town it needs a good pc to run it. I run 60fps throughout the town but run a 1080.

**Comment by DanielBeard83** [comment]
The performance issue was from my first download of the map, which was unfortunately not the official one. Since I got the official DL from the facebook page, no performance issues.

**Comment by BROADACRES16xFS17MAP** [comment]
Excellent great to hear
