### ISSUE TITLE
Floating drain and invisible wall

### ISSUE THREAD

**Issue by trckbldr88** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#29]
Next to ausveg building there is a floating drain. And at the end of it is a invisible wall

**Comment by spectrum69** [comment]
picture please

**Comment by babylon5657** [comment]
![screenshot 3](https://user-images.githubusercontent.com/32924811/32138819-b833e3b8-bc31-11e7-82fa-389585636dc9.png)
 I think he is referring to this at the AusVeg area just to the north of the compost plant Also in the car park area the parking lines are hovering off the ground as well

**Comment by trckbldr88** [comment]
Yes to both

**Comment by BROADACRES16xFS17MAP** [comment]
Ah you have the old version please download new one on our approved sites for fixes

**Comment by trckbldr88** [comment]
I have the new version

**Comment by BROADACRES16xFS17MAP** [comment]
Can you show us a pic of the floating drain? You have V1.1 and its a new game?

**Comment by trckbldr88** [comment]
It's 1.1. Not new game. I'll try that and see what happens

**Comment by BROADACRES16xFS17MAP** [comment]
No worries let us know how you go. :-)

**Comment by trckbldr88** [comment]
Thanks. I will. And keep up good work

**Comment by trckbldr88** [comment]
I new version 1.1 and new game.  The lines still float in parking lot and
the grate still floats near building

On Oct 28, 2017 23:49, "Matthew Masetta" <trckbldr88@gmail.com> wrote:

Thanks. I will. And keep up good work

**Comment by BROADACRES16xFS17MAP** [comment]
Can we grab a photo of the grate please so we can fix for newer update. Thanks
