### ISSUE TITLE
The world is turning black

### ISSUE THREAD

**Issue by Napoleon231187** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#30]
Not quit sure what cause this issue 

http://steamcommunity.com/sharedfiles/filedetails/?id=1183614979

according to my system cpu and gpu are not even by 50% 

My system is windows 10  
cpu : I7 6700
GPU :amd readon 8gb
ram: 16gb 

so should be enough hmmm any one a solution to it ?

**Comment by BROADACRES16xFS17MAP** [comment]
Not sure if you posted this issue before we shut down for a bit. It's your graphics card either on its way out or has issues. Try updating your card to the latest driver.
