### ISSUE TITLE
Missing gates to the forest area??

### ISSUE THREAD

**Issue by atb555ro** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#31]
Hi guys, i see everyone start woodwork near area of pallets factory......but i want to go in the forest that surround the map...and surprize...i don't find any gate to go through there!:))...i just fly all arround the map over the fence but i dont see any gate....or maybe that area is not for harvesting wood?.....im sure it is....but how we must get inside there??:)))  
![how to cross fence](https://user-images.githubusercontent.com/32667325/32138917-b99b70fa-bc44-11e7-807b-b0e97a53f461.jpg)

![fly](https://user-images.githubusercontent.com/32667325/32138927-07e345da-bc45-11e7-8a90-01e0eafdfb96.jpg)

...Maybe i do something wrong...idk...or maybe this fence must be cutted by chainsaw....:)))

If you can help me guys i will appreciate1:))

Great map, congratulation to all involved!!!

**Comment by BROADACRES16xFS17MAP** [comment]
Boundary Trees are for decoration only. They are harvest able but we have added plenty of trees in the forest for this purpose. Boundary fences have collisions so unless you teleport into that area you wont be able to harvest them. Feel free to play as you wish but as a map maker its how we built it

**Comment by Rene-Pedersen** [comment]
It is also possible to use a couple of placeable ramps on either side to get across if you insist on going against Ben's wishes ;-)

**Comment by atb555ro** [comment]
Hello guys, tnx for your answer!! I dont want to report this like an issue of the map...it was more like a question, is nothing to say about how is done the map or Ben wishes because the map are great and run perfect for me till now! ..it was more like "..what if i go there to "stole" some logs?!! :)))   I think also at some ramps...but it will be tricky to go through with trailers....im affraid to not remain suspended or something:))  
Great job Ben, you give us alot of work now...our wife's are "very happy" since map was released, !:P:))))

**Comment by BROADACRES16xFS17MAP** [comment]
All good we prefer even questions here as it helps us to look forward for possible cjanges going forward. Keep posting and happy playing.

**Comment by BROADACRES16xFS17MAP** [comment]
All good we prefer even questions here as it helps us to look forward for possible changes going forward. Keep posting and happy playing.
