### ISSUE TITLE
When I enter a vehicle the game freezes

### ISSUE THREAD

**Issue by Primeval82** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#33]
When ever I get in a vehicle the game freezes up. I have taken all the mods off to see if there is a conflict there but it still freezes. I can walk around okay.

**Comment by BROADACRES16xFS17MAP** [comment]
What are your pc specs and what settings are you on i.e. low, med, high. These issues are related to pc specs and your GPU size.

**Comment by Primeval82** [comment]
I've got MSI GE72VR GRF Apache Pro, with a Geforce GTX 1060, an i7-6700HQ cpu and 16 gig ram. All the other maps play okay on High settings.

**Comment by BROADACRES16xFS17MAP** [comment]
Which vehicle do you get into?

**Comment by Primeval82** [comment]
Any vehicle.

**Comment by BROADACRES16xFS17MAP** [comment]
Can you upload your log please with the freeze reconstructed. Just drag and drop log into this box when you reply. Have't had any other recorded issues of this so not sure what it is at this stage. Also try selling all your mods from in game then buy a new one. Have you made sure all the mods we supplied are in the mods folder?

**Comment by Primeval82** [comment]
Error: Failed to open xml file 'C:/Users/alexx/Documents/My Games/FarmingSimulator2017/mods/Broad_Acres/modDesc.xml'.
Load mod: Broad_Acres
Error: Missing descVersion attribute in mod Broad_Acres

I have redownloaded it and still didn't work. I'll download it again and see id the XML file is working correctly. I might have gotten a bad copy.

**Comment by BROADACRES16xFS17MAP** [comment]
May have mate. Keep trying and if no luckk upload your log. Let us know either way thanks.

**Comment by Primeval82** [comment]
I will let you know how it goes. Thanks for helping out and I look forward to playing.

**Comment by BROADACRES16xFS17MAP** [comment]
Any update or can I close issue?

**Comment by Primeval82** [comment]
I have been able to get the game working, so you can close the issue now. Thanks for putting out a great game. Maybe in the next one you can put in the Bundy factory as they are adding sugar cane in the upcoming new game. Maybe even a Barra farm. Thanks for your help.

**Comment by BROADACRES16xFS17MAP** [comment]
Great idea we have the room. Ill mark this post for new version to remind me.!

**Comment by BROADACRES16xFS17MAP** [comment]
Primeval82, Road Runner on Facebook site has the same issue. Can you let us know how you fixed it please?

**Comment by Primeval82** [comment]
I sent a message this morning regarding this issue. I don't now if it helped. All I did was unselect the mods and then reinstate them a few at a time to see what was wrong. But as it was pointed out today in the posts it might have been something to do with his rig.

**Comment by BROADACRES16xFS17MAP** [comment]
All good thanks mate. I see hes fixed it

**Comment by Jasmaz77** [comment]
I have the same problem just started the new game today its on easy level.

**Comment by Jasmaz77** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1440494/log.txt)

**Comment by Jasmaz77** [comment]
I want to play the game but can't I can't even enter a vehicle the game just freezes up!!

**Comment by BROADACRES16xFS17MAP** [comment]
I see your issue, you have put the whole package in as a zip. You need to open that zip and place the Broadacres.zip in seperately. Here is your error.

Error: Failed to open xml file 'C:/Users/Jason/Documents/My Games/FarmingSimulator2017/mods/Broad_Acres_Package/modDesc.xml'.

**Comment by Bundy-Bear** [comment]
From reading the log file
Point one - unzip Broad_acres Package and place Broad acres and the LS540 into your mod folder. (not the package file)
Point two - unzip Toll Complete and place the 7 zip files into your mod folder (not the TOLL Complete file)
When you start game Unselect your other maps

**Comment by BROADACRES16xFS17MAP** [comment]
Joys of new update is you dont have to unselect maps anymore!! :-)

**Comment by Jasmaz77** [comment]
I dont have other maps selected when i use this map.

**Comment by Jasmaz77** [comment]
![fs17 error](https://user-images.githubusercontent.com/33343839/32367557-77b90396-c0bd-11e7-9b33-36ba1f9fa8f2.PNG)

**Comment by BROADACRES16xFS17MAP** [comment]
repost log now please

**Comment by Jasmaz77** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1440593/log.txt)

**Comment by Jasmaz77** [comment]
This is really frustrating.

**Comment by Jasmaz77** [comment]
How do i know i have the latest version of FS17 1.5.1.1? does it auto update through steam?

**Comment by BROADACRES16xFS17MAP** [comment]
With steam I heard yes it does. If PC like me you have to do it manually

**Comment by BROADACRES16xFS17MAP** [comment]
Remove all your mods and run map only. You have alot of mod errors not related to our map. Run map only and see if it loads.

**Comment by Jasmaz77** [comment]
ok

**Comment by BROADACRES16xFS17MAP** [comment]
Your ground modification mod is three pages long in errors

**Comment by Jasmaz77** [comment]
how do i get courseplay5.zip i cant find it anywhere!

**Comment by BROADACRES16xFS17MAP** [comment]
I would get the map loaded then work your way up from there mate

**Comment by Jasmaz77** [comment]
Ok it's working now.  Could you figure out which mods were conflicting from my log file?

**Comment by Jasmaz77** [comment]
my ground modification map? is 3 pages long in errors? ground modification MOD you mean?

**Comment by BROADACRES16xFS17MAP** [comment]
okay cool have a look in your log and it will say error and then the mod that's causing issues. Remove them or add 5 at a time to see which ones are causing the map to freeze

**Comment by Jasmaz77** [comment]
ok i will add a few at a time, bare with me and thanks for your help.

**Comment by BROADACRES16xFS17MAP** [comment]
no sweat mate

**Comment by Jasmaz77** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1440772/log.txt)

**Comment by Jasmaz77** [comment]
i took out about 5 or 6 mods out of the mod folder in FS17, and in the game i have so far "selected" about 6 and will go from there.

**Comment by BROADACRES16xFS17MAP** [comment]
Load mod: ZZZ_PlayerSpeed (Version: 2.0)
Error: Can't load resource ''.
Error: Can't load resource ''.
Error: Can't load resource 'C:/Users/Jason/Documents/My Games/FarmingSimulator2017/mods/Ertrag_neuhaus/texturen/store.dds'.
Warning (compatibility): Texture C:/Users/Jason/Documents/My Games/FarmingSimulator2017/mods/FS17_NH_CR1090_CDYAY_ModLandNet/store_newHollandCR1090.dds width or height doesn't equal 2^n.
Warning (compatibility): Texture C:/Users/Jason/Documents/My Games/FarmingSimulator2017/mods/FS17_KroneZX450/store_krone_ZX450.dds width or height doesn't equal 2^n.
Warning (compatibility): Texture C:/Users/Jason/Documents/My Games/FarmingSimulator2017/mods/GreatfieldsBETA3_ModLandNet/maps/map01_preview.png width or height doesn't equal 2^n.
Error: Can't load resource 'C:/Users/Jason/Documents/My Games/FarmingSimulator2017/mods/Ertrag_neuhaus/texturen/store.dds'.
Warning (compatibility): Texture C:/Users/Jason/Documents/My Games/FarmingSimulator2017/mods/FS17_KroneZX450/store_krone_ZX450.dds width or height doesn't equal 2^n.
Warning (compatibility): Texture C:/Users/Jason/Documents/My Games/FarmingSimulator2017/mods/FS17_NH_CR1090_CDYAY_ModLandNet/store_newHollandCR1090.dds width or height doesn't equal 2^n.

**Comment by BROADACRES16xFS17MAP** [comment]
still have TOLL as a zip aswell

Error: Invalid mod name 'TOLL COMPLETE'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

**Comment by Jasmaz77** [comment]
ok ive fixed the toll one, i still had the full file in the mods folder as well as the other 7 files, 
what are the mods above that are giving errors?

**Comment by Jasmaz77** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1440862/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
the rest arent bad so shouldnt cause you too much issues

**Comment by Jasmaz77** [comment]
ok
