### ISSUE TITLE
Just a question concerning cotton

### ISSUE THREAD

**Issue by schniedertoenz** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#37]
Hi there,

first of all I want to thank you for this great map and the investment of so much time and effort.

Just one question: Is there anything else that can be done with "cotton" instead of selling at Viterra trailer sell?

Best regards.

GG

**Comment by spectrum69** [comment]
yes, of course, you can press and sell the ball

**Comment by schniedertoenz** [comment]
Press with Goweil press and sell where? Same as wool?

**Comment by BROADACRES16xFS17MAP** [comment]
You can bale the cotton and sell at.the hay area

**Comment by schniedertoenz** [comment]
Thanx
