### ISSUE TITLE
Do not download from Modhub.us

### ISSUE THREAD

**Issue by jcmout** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#39]
I downloaded the newest map from the Modhub.us site and today the broadacers has corrupted all my maps. It will not let any of my maps load because it is trying to open them as Broadacres. Even the maps that came included in the game. Please look in to this as the only way to resolve this was to completely remove the game and not use the Broadacres map.

**Comment by aceman91** [comment]
Anything on mod sites are not the real deal. Do not download from them. There is now no download links to get this map as a few messed it up for all of us

**Comment by rwzippy** [comment]
Hi aceman. The map is now released for public download. Thank you for your concern.

**Comment by BROADACRES16xFS17MAP** [comment]
Jc mount please see our facebook page for correct links. As with all games when loading another map always remove other maps from the mod loading screen (were you can tick them on or off). This is also covered in the manual.
