### ISSUE TITLE
Error in Log duing "night work"

### ISSUE THREAD

**Issue by schniedertoenz** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#40]
Hi there,

working at night I get the following error:

Error: Could not parse GISL program.
(164): ERROR: 'modelViewMatrix' : undeclared identifier 

Error: Failed to compile shader 3ECE0DEE-00023800-00000000-06180010.

Error comes several times. I do not have a clue what causes ist.

Any hint?

Best regards

**Comment by BROADACRES16xFS17MAP** [comment]
Were qre you at when it occurs.?

**Comment by BROADACRES16xFS17MAP** [comment]
*are

**Comment by schniedertoenz** [comment]
I have to check.

**Comment by spectrum69** [comment]
this problem is due to a bad harvester for the cotton or a bad harvest for the carrots, onion ... use the pack holmer for sudhermenn map

**Comment by schniedertoenz** [comment]
I removed the cotton harvester (JD 95XX) but the error still occurs.
Seems to be between the Case shop and the shell fuel station.
I cannot locate it precisely.

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks we'll test, sometimes its just an old shader in one of the mods. Hard to narrow down when there are mods running as well as numerous factories. We'll give it a run in due course and see if we can replicate.

**Comment by schniedertoenz** [comment]
thx

**Comment by BROADACRES16xFS17MAP** [comment]
Finally found the issue by luck. Was the Hay Sale building and lighting scripts. All fixed for V2. Thanks for the report been the hardest one yet to find :-)
