### ISSUE TITLE
cant sell loose straw at the sell trigger

### ISSUE THREAD

**Issue by JackG969** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#41]
what title says i sit in the area with a trailer full of 500k liters of straw and it wont let me sell it when it says i can in the manual.

**Comment by BROADACRES16xFS17MAP** [comment]
Just need some more info re type of straw and how collected etc please.

**Comment by ledge1978** [comment]
Does the tip trigger show?

**Comment by BROADACRES16xFS17MAP** [comment]
What mod trailer you are using? Then we can  test. Maybe a pic

**Comment by BROADACRES16xFS17MAP** [comment]
Mod trailer i meant

**Comment by BROADACRES16xFS17MAP** [comment]
![23157911_1657153230982975_110793931_o](https://user-images.githubusercontent.com/7673205/32217205-39306490-be77-11e7-93ab-ce06c4e32f6d.png)

JackG969 my tester Victor has tested this issue and working okay. Hopefully this pic will help. Pleae let us know if you have fixed it so I can close the issue. Thanks.

**Comment by spectrum69** [comment]
![fsscreen_2017_10_31_11_29_11](https://user-images.githubusercontent.com/25110957/32219556-d659a7de-be2e-11e7-9b35-42545dd7e7a5.png)
![fsscreen_2017_10_31_11_22_23](https://user-images.githubusercontent.com/25110957/32219557-d6be6d7c-be2e-11e7-85be-001c9af5cfcb.png)
![fsscreen_2017_10_31_11_22_21](https://user-images.githubusercontent.com/25110957/32219620-0ef54274-be2f-11e7-9313-b6fd94fa6def.png)
![fsscreen_2017_10_31_09_57_25](https://user-images.githubusercontent.com/25110957/32219656-3a82428e-be2f-11e7-9ca9-7dac5374593b.png)
![Uploading fsScreen_2017_10_31_09_56_39.png…]()

**Comment by JackG969** [comment]
i have tried it again after looking at your guys pics it still doesn't let me no matter where i am in the trigger it could be the mod i am using, i am using the silospacesa all i have done is changed the capacity one it. i took a steam screen shot here it is https://steamuserimages-a.akamaihd.net/ugc/856108485265466706/DFE559F4CE86B37B6AD1680A58B80194420DDCD7/

**Comment by ledge1978** [comment]
From what I can see you’re not in the tipping area. Check the pink trailer pic and look in the bottom right corner at the trailer icon that’s the tip trigger

**Comment by BROADACRES16xFS17MAP** [comment]
Have you tried a.different mod?

**Comment by JackG969** [comment]
thx for the help guys it was just that mod that wasn't letting me do it tried a different one and it let me sell it.

**Comment by BROADACRES16xFS17MAP** [comment]
No problems happy to help
