### ISSUE TITLE
Static actor moved

### ISSUE THREAD

**Issue by schniedertoenz** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#42]
Hi again,

I've found another issue:

Warning (physics): Static actor moved (Timb:wagon_vis) 
(message about 400 times after another without cr/lf, reads as a single line in console view)

Seems to be related to using the train, perhapst when transporting wood.

Best regards

GG

**Comment by BROADACRES16xFS17MAP** [comment]
HI,

We believe this is caused due to the static timber logs and a non static log trailer in the game. Its a giants glitch and not much we can work with. We had it in testing every now and then as well but appears not fixes. Sorry.
