### ISSUE TITLE
Railway lines profile too high

### ISSUE THREAD

**Issue by Duckzorly** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#43]
While the profile of the RW lines is very good in its aesthetics it does create an issue for some vehicles being so high.  So in transition areas (gravel road/RW line), some vehicles tend to get caught on the rails.  For example, the New Holland CR10.90 catches its trailer hitch.

Either more crossings need to be implemented, or raise the ground level/embed RW line lower in the ground at these places to allow more consistent passing over the lines.

Images as an example attached
![20171101142501_1](https://user-images.githubusercontent.com/33297641/32299165-b1c11b2a-bfa8-11e7-9d38-9a85f909a2ac.jpg)
![20171101142519_1](https://user-images.githubusercontent.com/33297641/32299167-b1f04b84-bfa8-11e7-9617-7c409f4a534e.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks we'll add more crossings in new version.

**Comment by BROADACRES16xFS17MAP** [comment]
Duckzorly I am just adding these in now. Was it just this one that needed done?

**Comment by Duckzorly** [comment]
The primary one that I have found thus far is the north east field (#3?) as you can't access the field gate road over the rroad on many vehicles

Haven't explored all the map yet!!!! lol

**Comment by BROADACRES16xFS17MAP** [comment]
lol that one is fixed. Ill leave it here and see if there are anymore
