### ISSUE TITLE
Graphics Rendering - TMR/Pig Food production

### ISSUE THREAD

**Issue by Duckzorly** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#44]
Whilst using the TMR and Pig Food production facilities, found that the rendering of the feed piles, is not clipped to the edge, or has been distorted allowing large gaps visible from all sides.

Images attached for clarity
![20171101114936_1](https://user-images.githubusercontent.com/33297641/32299235-f76814d0-bfa8-11e7-9026-8661a55d6a0d.jpg)
![Uploading 20171101114945_1.jpg…]()

**Comment by slowboat** [comment]
I am also having that problem.

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks well have a look

**Comment by BROADACRES16xFS17MAP** [comment]
Can you tell me how much you put in please? I see the issue and will have to refix in newer version

**Comment by Duckzorly** [comment]
I believe it would have been 100k of each - maximum load for the inputs

**Comment by BROADACRES16xFS17MAP** [comment]
Yeah thought as much. Well fix it for new version. Cheers.

**Comment by BROADACRES16xFS17MAP** [comment]
Removed planes as well as floating numbers and video screen
