### ISSUE TITLE
Problem with loading screen 

### ISSUE THREAD

**Issue by dougmarini** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#45]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1435860/log.txt)
 
Hi guys. First of all, I'm sorry about my English if I wrote something wrong. 
My name is Douglas, and I tried to play with your map, but it starts to load and load, it never ends. I let my pc on for about 1 hour and a half, and it was still loading. 
I put my log.txt here (if it doesn't appear, tell me and I will try to put here again)
I don't think its my computer, it isn't the best one, but it is still good. 
Hope you guys could help me to see if I do something wrong, thanks

**Comment by BROADACRES16xFS17MAP** [comment]
Hi dougmarini, try removing all your mods from loading screen and just run map on its own. If it loads then you have a bad mod. Make sure no other maps are selected aswell. Let us know how you go.

**Comment by dougmarini** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1436070/log.txt)

I remove every mod that I have, even the mods that comes with the Broad Acres, it stills stays loading for a long time, and never finish...

**Comment by BROADACRES16xFS17MAP** [comment]
Okay looked at log. Couple of questions.

1) have you unzipped the package that you downloaded and placed individual zips into the mod folder?

2) have you checked you have a correct version and downloaded it from a supported link. (See pinned post in our facebook page to check)

3) Has anything been modified with the map by yourself prior to loading?

**Comment by BROADACRES16xFS17MAP** [comment]
Looking at your log you still have mods being loaded as well. Maoe sure they are all unticked.

**Comment by dougmarini** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1436677/log.txt)

So, I deleted every file that i had in my mods folder, put the Broad Acres package, unzipped it, and unzipped the Toll Complete Zip. I started the game, iniciate a new game, and deselect two mods that comes with the game: 
MT700E Field Viper and T Series Cow Edition
And then I started the game, it stills gets stuck in the loading screen and never ends. 

About the version, I downloaded the folder from the facebook page yesterday, the first link. And I don't modified it

**Comment by BROADACRES16xFS17MAP** [comment]
okay there is an error that 800 people that have downloaded it are not reporting so not sure what is going on with yours but here is the error. I have checked our package we uploaded and its all there. Please make sure you haven't deleted this out of the zip folder. No one else has reported this error so not sure what you have done.

Error: failed to load i3d file 'maps/models/train/train/PalettenWagon/wagonTimber1.i3d'
Warning (Script): Unknown entity id 0 in method 'getChildAt'.
LUA call stack:
  =dataS/scripts/trainSystem/RailroadVehicle.lua (0) : getChildAt
  =dataS/scripts/trainSystem/RailroadVehicle.lua (0) : loadInternal
  =dataS/scripts/trainSystem/TrainSystem.lua (0) : load
  =dataS/scripts/OnCreateLoadedObjectsManager.lua (0) : load
  =dataS/scripts/missions/mission00.lua (0) : loadFromAttributesAndNodes
  =dataS/scripts/missions/mission00.lua (0) : loadVehiclesFinish
  =dataS/scripts/BaseMission.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0)
  =dataS/scripts/utils/Utils.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0) : loadSharedI3DFile
  =dataS/scripts/BaseMission.lua (0) : load
  =dataS/scripts/missions/mission00.lua (0) : loadVehicle
  =dataS/scripts/missions/mission00.lua (0) : loadVehiclesStep
  =dataS/scripts/BaseMission.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0)
  =dataS/scripts/utils/Utils.lua (0)
Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (604): expectedType == Value::VoidType
LUA call stack:
  =dataS/scripts/trainSystem/RailroadVehicle.lua (0) : getWorldTranslation
  =dataS/scripts/trainSystem/RailroadVehicle.lua (0) : loadInternal
  =dataS/scripts/trainSystem/TrainSystem.lua (0) : load
  =dataS/scripts/OnCreateLoadedObjectsManager.lua (0) : load
  =dataS/scripts/missions/mission00.lua (0) : loadFromAttributesAndNodes
  =dataS/scripts/missions/mission00.lua (0) : loadVehiclesFinish
  =dataS/scripts/BaseMission.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0)
  =dataS/scripts/utils/Utils.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0) : loadSharedI3DFile
  =dataS/scripts/BaseMission.lua (0) : load
  =dataS/scripts/missions/mission00.lua (0) : loadVehicle
  =dataS/scripts/missions/mission00.lua (0) : loadVehiclesStep
  =dataS/scripts/BaseMission.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0)
  =dataS/scripts/utils/Utils.lua (0)
Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (604): expectedType == Value::VoidType
LUA call stack:
  =dataS/scripts/trainSystem/RailroadVehicle.lua (0) : getWorldTranslation
  =dataS/scripts/trainSystem/RailroadVehicle.lua (0) : loadInternal
  =dataS/scripts/trainSystem/TrainSystem.lua (0) : load
  =dataS/scripts/OnCreateLoadedObjectsManager.lua (0) : load
  =dataS/scripts/missions/mission00.lua (0) : loadFromAttributesAndNodes
  =dataS/scripts/missions/mission00.lua (0) : loadVehiclesFinish
  =dataS/scripts/BaseMission.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0)
  =dataS/scripts/utils/Utils.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0) : loadSharedI3DFile
  =dataS/scripts/BaseMission.lua (0) : load
  =dataS/scripts/missions/mission00.lua (0) : loadVehicle
  =dataS/scripts/missions/mission00.lua (0) : loadVehiclesStep
  =dataS/scripts/BaseMission.lua (0)
  =dataS/scripts/vehicles/Vehicle.lua (0)
  =dataS/scripts/utils/Utils.lua (0)
Error: Running LUA method 'loadSharedI3DFileFinished'.
dataS/scripts/trainSystem/RailroadVehicle.lua:0: attempt to perform arithmetic on a nil value
Application exit request forced.
Application exit request forced.
