### ISSUE TITLE
Hired Help Glitch

### ISSUE THREAD

**Issue by Gaminghog763** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#46]
I have left 2 videos here that I have published to youtube. The first one is of my demonstration. The second one is of proof that no other mods were running other than the plow mod to possibly interfere with the test and also proving that it was a fresh save. I have spoken with Ben and he told me to do this here so I am. Sorry if the production value is minimal. 
1st Video: https://youtu.be/Av4srCdTBfY
2nd Video: https://youtu.be/pAJglI8e4Mk

**Comment by BROADACRES16xFS17MAP** [comment]
okay so I have tested with a Tiger 10l cultivator and it works fine. I have attached a photo to prove. Send me a link to the modded ones and I'll try again. Only thing I can think of is the mod. Although it works in other maps this has chopped straw which may affect the mod.  My suggestion would be to sow the field and then retry the plough after that once chopped straw is gone . Also try with the Tiger10l  which is standard for game and report back. Also just checking you have a supported version as per our facebook links?


![fsscreen_2017_11_02_17_19_38](https://user-images.githubusercontent.com/7673205/32313315-26b0ffce-bff2-11e7-9b01-a1713a66c045.png)


I haven't had any other reports for this issue as you can see.

**Comment by Gaminghog763** [comment]
It was also with the base game plow though and with chopped straw on my legit world as well mind you, so it isn’t the plow mod it has to be another underlying issue.

**Comment by BROADACRES16xFS17MAP** [comment]
I would suggest with the chopped straw it may miss the ploughing in the first instance then need it in the following after harvest or sowing etc etc second time round.. I would cultivate then plough and see if that works.

**Comment by Gaminghog763** [comment]
Ok I will indeed go to cultivate. It may be that default soil state confusing the hired help. Sounds like a very plausible solution. When I get a chance that’s what I will do and report back to you

**Comment by BROADACRES16xFS17MAP** [comment]
Okay so there isn't an issue here and is now resolved.

For other users, check PDA of when the paddocks (fields) need ploughing. With chopped straw you cultivate after a harvest or before seeding. This then adds fertilizer into the field and will show as such on the PDA. Check the PDA on each occasion you harvest for when it requires to be ploughed. From memory usually every third time pending settings. Hope this helps others.
