### ISSUE TITLE
With the new FS update 1.5, I am unable to open/close gates

### ISSUE THREAD

**Issue by slowboat** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#47]
I downloaded the latest FS update this morning, 1.5,, now I am unable to open or close gates. I have tried in vehicles and standing close to gates with the same results. Prior to the update, I did not have this issue.

**Comment by slowboat** [comment]
Please note that this is on a saved game and not a new game.

**Comment by slowboat** [comment]
Update, I just started a new game and I am able to open the gates if I am outside of the vehicle. I tried to open a gate while inside a vehicle but no luck. I can only open the gate(s) if I am outside the vehicle. Should I just start a new game would be my question now?
 I have decided to just start a new game so all of the fields will open to me.

**Comment by Duckzorly** [comment]
This is a script problem associated with the 1.5.1 update, not so much the game. If you are using the Animate Object/Open Gates mod then disable it and then when in game if you get out of the vehicle the gates will work. The script is broken and won't allow use from in tractors atm
