### ISSUE TITLE
Suggestions for V2

### ISSUE THREAD

**Issue by BROADACRES16xFS17MAP** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#49]
Leave all your suggestions here. We may not comment but will definitely read them all and take into consideration.

**Comment by Duckzorly** [comment]
Perhaps (as an aside to the gates themselves) reconsider the placement of them. Noting it being such a big map, people are going to want to use bigger equipment.. gate locations (imo) should placed in the most logical and practical locations.  For example to ensure relatively easy access for a combine that is towing its header on a header trailer, or for a 3 or 4 trailer Road Train combo.

Secondly, a straw storage compatible silo (or modify the existing to take straw) in the northern storage area (I know we could put placeables, but minimising object loading on top of map should take precedence to ensure good performance.

Thirdly, hmm for now I can't think of it - will be back later to add more!

Lastly - keep up the outstanding work... loving it.

**Comment by ReedME** [comment]
I’d like to see some slight variations in the terrain, because there is nowhere in the world except maybe Antartica which is 100% flat, every farming area in Australia that I’ve visited etc has always had hills and such.

As such I’d like to see the map get some slight changes in elevation throughout would make it a little more interesting and change up the scenery a little

I would also like to see a change to the scenario, to utilise a system like stappenbach 17 where the player buys different farm areas with different focuses, in addition to the fields, plus a more challenging scenario where the player starts with just one or two fields and a bunch of old machinery instead of the best of the best

‘Joe bloggs has inherited his grandfathers run Down farm and needs to make a name for himself in the broad acres district, starting with Old worn equipment, a small field and a small loan, can joe become the biggest in the industry?’

**Comment by SunkenL** [comment]
Sometimes i think that some things isnt scaled correctly for a 16x map.
Some of the storage isnt big enough. Like the foragemaker and the compostmaker. Put a extra zero on all the storage and factorys or something

A good example is the trains. 250000/wagon and 83km/h. For a 16x map this is way to low. 


## _

> Thanks and we'll look into storage values. With regards to the train we have to be careful for load though. Make it too big and trains wont pull fully loaded. Its a tricky happy medium

_

**Comment by ReedME** [comment]
@SunkenL 

I think 250k per wagon is fine, I know it is 250k Litres, which roughly translates to 0.6 KG per Litre in the case of grain, so roughly speaking thats 125 tonne. Most train wagons in reality are between 60-100 tonnes per wagon. So I think that 250k Litres is a really good figure, pretty realistic. 

I do agree that the storage and factories could be bigger but not unrealistically so!

**Comment by auusie-mark** [comment]
hi ben I am part of fi and tazzie nates server and discord. I was just wandering with the trains going through each farm would it be an idea so that you could not only load the trains but unload at the farms.

> Already on that one!

**Comment by Rene-Pedersen** [comment]
I would love to see more factories / sell places maybe combined with the script set from "Gift of the Caucasus" where you have the in-game menu to view all places and their stock as well as you can buy factories to earn even more money.

> I thought we placed alot in but what we're you thinking?

**Comment by SunkenL** [comment]
A fun thing for the BGA in the next version whould be a really large BGA-silo. Like Hobbs farm has. I think that could be a nice addition to the map

**Comment by ravenlord69** [comment]
1.I would love to see the factories storage of raw materials increased alot. We have these huge fields but factories only hold 50k of raw materials. No farmer would plant a huge field of a crop to only have demand for 50k of it.
2. Make the trees in the animal pastures non-collision as unless you want to spend millions on a grass field as it causes havok with courseplay.
3.Thats all i got great map.

**Comment by BROADACRES16xFS17MAP** [comment]
#51

**Comment by BROADACRES16xFS17MAP** [comment]
Posted in incorrect area. Moved here to collate all suggestions

As I'm playing with seasons and hard difficulty I have only 1 harvest behind me my experience is only from start of the game and starting fields 1,17,20-22, if it is different with other ones please skip these comments.Gates and fences - As have been said you will not make them bigger or completely remove them because they are real. But please make a bigger space between edge on the fields and fences. At the current setup I will come in my combine harvester with header on the trailer, park it on the edge drive through crops, destroy it ofcourse, attach my header and then I can start harvesting. As fields are big ok I can miss few liters of grain but then big issue with fences is on the table. I'm using CoursePlay (CP) with course for combine and course for the tractors with chaser bins. Course for the combine must be always set with pipe facing out the field (which is real, because any farmer will drive tractor into the crops for unloading the combine) but there is simply not enough space between combine and fences to get tractor with chaser bin next to the combine. Tractor always get stuck and you have to sort it manually, which is fine now when I have few small fields but when I will have big ones and machinery setup on many of them I cannot imagine how I will make harvest in time window when using seasons mod ( I have 12 days for any season and time set 5x which is pretty real I think). Yes in game you can set course for the combine with pipe facing inwards field, where is lots of space, but first there is still crop and second CP tractor will crash into combine in 99% with this setup (he will do it even when crop is already harvested on that part anyway) and you again have to sort it manually. Yes I can setup combine to unload itself like in real life but again it is time consuming to set it after first header to normal course. In real life when running two or more combines they will unload second first and they switch positions, but unfortunately game/CP is not so smart yet and you have to do it only manually again. There are no problems with other cultivating/seeding/spraying machinery, chaser bins can even nicely unload over the fence with trucks or mother bin waiting other side.Liquid manure - would be nice if you will be able to make it from digestate/slurry and water, similar way like you make solid one. As for the slurry itself I don't have animals yet so I don't know how big tanks are there but I would like to see big pool with BIG capacity for that (I like to use it for fertilising and usage on those big fields will be enormous).Fuel - you can make your own so petrol station which we can fill and use for free near each storage area will be nice. (I know you can buy fuel from those small shell tanks)Industry - as I haven't done any production yet this is only question. Hope all product can be picked up by forklift and loaded and stacked to any trailer not only TOLL ones. They are nice but I don't want to have only those in my farm/map. Ofcourse those grain hoppers with absolutely unreal capacity are stupid I uninstaled them straight away.And as somebody stated before some hills wil be nice addition too, but it really depends what part of AUS you trying to show us.S*** it is long, sorry for complaining...Thanks I wont reply to all but seasons mod isnt added as yet as Australian seasons aren't made. We have someone looking at that as we speak to be added into other versions of the map. You can use any trailer you like except the toll food trailer to convey from the toll depot as we have added the corresponding pallets so they look the same in the truck. The rest we'll take into consideration thanks :-)
--

**Comment by Bundy-Bear** [comment]
Can another green direction sign similar to the one at the other end of town be added at the BP end of town ie near field 4/20

> Easy done

**Comment by aussiegamer2017** [comment]
i would like to see a faster train lol, and maybe the gates arould the fields oppiset the bakery turned around as its hard getting a b-double in there

**Comment by babylon5657** [comment]
Additional pallet making factory on the map as 1 cant keep up with demand

**Comment by Sav19** [comment]
I would like to see train unloading points at the storage areas. So I can use the train to transport crops from the field to the silos.


> hi ben I am part of fi and tazzie nates server and discord. I was just wandering with the trains going through each farm would it be an idea so that you could not only load the trains but unload at the farms.Already on that one!

**Comment by BROADACRES16xFS17MAP** [comment]
Already completed for V2 as above Sav19

**Comment by Buhler0014** [comment]
i would like to see markers for triggers,
storage for hay pellets, 
wider gates
maybe a spot at farms for a placeable tractor garage (machine shed)
