### ISSUE TITLE
Some bug in BGA

### ISSUE THREAD

**Issue by SunkenL** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#50]
Dont know if it is the map or some other wierd thing
![fsscreen_2017_11_02_21_50_34](https://user-images.githubusercontent.com/24603095/32361635-a17644ce-c062-11e7-9f90-99a0e06fc18c.jpg)

Where did it all go?

**Comment by BROADACRES16xFS17MAP** [comment]
hmm no idea on that one, is it saved game before new update? I know there were some fixes for BGA in there.

**Comment by SunkenL** [comment]
Yes a saved game before FS17 update. 
The map is first version

**Comment by BROADACRES16xFS17MAP** [comment]
Is map 1.1? In saying that it would be the update as bga was "improved".

**Comment by SunkenL** [comment]
The map is the first version that came out the day of release.

**Comment by BROADACRES16xFS17MAP** [comment]
Ah you will have a load of issues with that one as a late script we implemented that day through a lot of things out. Download the latest form our pinned post and you should be fine.
