### ISSUE TITLE
Suggestions for V2

### ISSUE THREAD

**Issue by Misamangame** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#51]
As I'm playing with seasons and hard difficulty I have only 1 harvest behind me my experience is only from start of the game and starting fields 1,17,20-22, if it is different with other ones please skip these comments.

1. Gates and fences - As have been said you will not make them bigger or completely remove them because they are real.  But please make a bigger space between edge on the fields and fences. At the current setup I will come in my combine harvester with header on the trailer, park it on the edge drive through crops, destroy it ofcourse, attach my header and then I can start harvesting.  As fields are big ok I can miss few liters of grain but then big issue with fences is on the table. I'm using CoursePlay (CP) with course for combine and course for the tractors with chaser bins. Course for the combine must be always set with pipe facing out the field (which is real, because any farmer will drive tractor into the crops for unloading the combine) but there is simply not enough space between combine and fences to get tractor with chaser bin next to the combine. Tractor always get stuck and you have to sort it manually, which is fine now when I have few small fields but when I will have big ones and machinery setup on many of them I cannot imagine how I will make harvest in time window when using seasons mod ( I have 12 days for any season and time set 5x which is pretty real I think). Yes in game you can set course for the combine with pipe facing inwards field, where is lots of space, but first there is still crop and second CP tractor will crash into combine in 99% with this setup (he will do it even when crop is already harvested on that part anyway) and you again have to sort it manually. Yes I can setup combine to unload itself like in real life but again it is time consuming to set it after first header to normal course.  In real life when running two or more combines they will unload second first and they switch positions, but unfortunately game/CP is not so smart yet and you have to do it only manually again. There are no problems with other cultivating/seeding/spraying machinery, chaser bins can even nicely unload over the fence with trucks or mother bin waiting other side.

2. Liquid manure - would be nice if you will be able to make it from digestate/slurry and water, similar way like you make solid one. As for the slurry itself I don't have animals yet so I don't know how big tanks are there but I would like to see big pool with BIG capacity for that (I like to use it for fertilising and usage on those big fields will be enormous).

3. Fuel - you can make your own so petrol station which we can fill and use for free near each storage area will be nice. (I know you can buy fuel from those small shell tanks)

4. Industry - as I haven't done any production yet this is only question.  Hope all product can be picked up by forklift and loaded and stacked to any trailer not only TOLL ones.  They are nice but I don't want to have only those in my farm/map. Ofcourse those grain hoppers with absolutely unreal capacity are stupid I uninstaled them straight away.

And as somebody stated before some hills wil be nice addition too, but it really depends what part of AUS you trying to show us.

S*** it is long, sorry for complaining...

> Thanks I wont reply to all but seasons mod isnt added as yet as Australian seasons aren't made. We have someone looking at that as we speak to be added into other versions of the map. You can use any trailer you like except the toll food trailer to convey from the toll depot as we have added the corresponding pallets so they look the same in the truck. The rest we'll take into consideration thanks :-)

**Comment by Misamangame** [comment]
Hello, yes I know  seasons isn't supported yet on this map, but it just adds more reality, even towards machinery use etc. Personally I have mid US climate enabled which I think is closest to Australia, even when I cannot plant sugar beet. Looking forward to see it in some upcoming versions. Keep up good work

> Thanks will probably be in V3 at this time as I haven't had the time to play with it. When I get a chance I will modify it to suit and then add it in

**Comment by griffinjohn24** [comment]
After almost a month of trying to download and play this HUGE map, I finally got to play lil bit BUT I do have some suggestions that should be looked into before new release. Now this is all I found so far and haven't traveled to every place on the map.
1) Added fruit type...Lettuce, Cabbage and Red Cabbage??
   

>  ** - If you view the map you will find they are already located in Aus Veg

2) 'Guide lines' to separate F15 & F19 and F2 & F3, looks like 1 complete field on both sections.

> This is just the PDA not showing due to the road being a mud road.

3) With such a huge forest area, why not think about adding like a pallet factory and sell point?

> See town there is a whole section dedicated to forrestry

4) There isn't a 'buy' icon for F16 (blue)

>It's only because the fuel icon is shadowing it, click the fuel icon and it will come up with F16

5) Why is there an option to buy F23 if it's just a parking lot?

> Buyable storage area for placeables or whatever you like to put in there. This was designed so you had to buy it first. Giants put a limitation that unfortunately it shows a field due to the sale icon.

6) Add another gate to the shop area, around where the tractors are sitting on the fence line.
7) English translation for cow display, the fill station next to the barn.

> Noted and will change

8) How about adding a digital display at the silos? Got tons of them but unsure what the yield is for each crop or what they can hold.

> If you place your trailer underneath each silo it will come up with a menu and show exactly how much and what fruit type you have

9) The drop off point for the carrots, onions, potatoes and sugar beets, could you add some kind of signage for these areas, located at start point far as I know.

> We added this in the manual. You can find it in the package or on our page.

10) How about making roads more 'road train' friendly? I'm pulling up to 3-5 trailers and some of the signs are a 'PITA'. (pain in the ***)

> Not deisgned for five trailers as we build it around some realism. 5 trailers dont exist in Australia (not farming were I am anyway) :-) We have widened some for V2 though to suit b-doubles or triples.

Like I said I just played long enough to find these small issues/concerns and haven't traveled all over. Sorry if I sound like a 'PITA' but I would like to play on a map that the owners are willing to listen to their players and try and fix/add things. I thank you for your time and patience.
