### ISSUE TITLE
Errant Texture on Field 18 an 3

### ISSUE THREAD

**Issue by Duckzorly** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#52]
Found this texture error in north western end of Field 18
![20171104005452_1](https://user-images.githubusercontent.com/33297641/32377734-b5133f4c-c0fc-11e7-8eaa-67a640111ce3.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks mate.

**Comment by BROADACRES16xFS17MAP** [comment]
Can I have a PDA photo of were this please?Having issues finding it.

**Comment by Duckzorly** [comment]
Coordinates are 459,411 on the PDA map.....took me a while to find it again myself lol
![20171105124424_1](https://user-images.githubusercontent.com/33297641/32411122-196e5398-c227-11e7-8446-af6dac867d8f.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Thankyou makes it a bit easier :-)

**Comment by Duckzorly** [comment]
Ben

Found another one at map coords 7677,523 - Field 3...

![20171105144159_1](https://user-images.githubusercontent.com/33297641/32411764-92a63a54-c237-11e7-86a2-db1207cae79c.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Fixed second one thanks mate
