### ISSUE TITLE
mp will not load past 27% for friends

### ISSUE THREAD

**Issue by baconm13** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#55]
When ever my friends try to join my mp game it freezes on there side at 27%. I have disable each mod individually and traced it to the KOTTE UNIVERSAL PACK V2.0.X. Even if all mods are disabled except this one it will not load for them.
my log~ [log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1442850/log.txt)
 friends log~ [log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1442855/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Just need some more information. Have you updated to newest version of farm sim on both pc's? Have you attempted to start a refreshed game? There have been server issues since the new update.

**Comment by BROADACRES16xFS17MAP** [comment]
The Kotte pack isn't ours so we cant support it however I'm guessing it still wont load?

**Comment by Bundy-Bear** [comment]
this might be part of the problem on both logs

Load mod: Broad_Acres (Version: 1.0)

**Comment by Bundy-Bear** [comment]
I changed my Kotte Universal pack to the version that is linked in the manual and I'm not getting any errors in my log associated to the Kotte.

**Comment by BROADACRES16xFS17MAP** [comment]
So is there still issues or have we fixed so I can close?

**Comment by baconm13** [comment]
we are playing right now with a fresh save. but as soon as i buy any of the water trailers no one can hook up to them and they float about a foot off the ground. also when i sell the trailer, two more appear and model in side each other. the shell trailer works fine.

**Comment by baconm13** [comment]
also this issue happened before and after the fs update. i have been trouble shooting as much as i can before i posted.

**Comment by BROADACRES16xFS17MAP** [comment]
No sweat no idea whats going on with the mods to be honest. Others have played MP and all good but unsure on those mods. Glad you in anyway. I'll close the issue as it doesn't appear to be Broad Acres itself.
