### ISSUE TITLE
Texture glitch on Field 20

### ISSUE THREAD

**Issue by Bundy-Bear** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#56]
As requested.

Minor glitch hence it hasn't been previously reported. 2 pics one after harvest and one after plowing. I left CP on so you can see how far off the fence it is.

![glitch](https://user-images.githubusercontent.com/32672100/32409706-d24e73de-c204-11e7-9667-353b572668d1.jpg)
![glitch1](https://user-images.githubusercontent.com/32672100/32409705-d218871a-c204-11e7-8c2e-df7524600ee7.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks mate
