### ISSUE TITLE
Main silo storage

### ISSUE THREAD

**Issue by Bundy-Bear** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#58]
I'm not sure if this is an issue or as designed. multifruit not accepted at the Main silo storage area. So far I have tried cotton rye and now millet.

![silo](https://user-images.githubusercontent.com/32672100/32411965-7622510a-c23d-11e7-912b-0665747f6996.jpg)

**Comment by SunkenL** [comment]
I Got the millet in on the other storagearea for getting it in the train. But the sellpoint dont accept millet even if the selllist says so:( . So now i have a full train with millet that i cant get rid of.

**Comment by BROADACRES16xFS17MAP** [comment]
Sorry guys. I will look at it later today and update the xml. Once done I'll upload it so everyone gets the fix. It will be just a matter of putting this file into the zip so no new saved game.

**Comment by BROADACRES16xFS17MAP** [comment]
I have added a new map01.xml on our page. Instructions on how to replace is noted on there.

**Comment by BROADACRES16xFS17MAP** [comment]
Let us know how it goes with a saved game.

**Comment by Bundy-Bear** [comment]
Works now thanks

**Comment by BROADACRES16xFS17MAP** [comment]
Cheers

**Comment by BROADACRES16xFS17MAP** [comment]
I've added a V2 appears millet was still missing off second train. Third time lucky
