### ISSUE TITLE
Town sellpoint doesnt accept millet from train

### ISSUE THREAD

**Issue by SunkenL** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#59]
I have a train full with millet that i cant get rid of now. 
The dropofpoint at the town dont accept it but the sellpointlist say that it will.
I could sell att the bunker 1 but there is no way to empty the train..

**Comment by BROADACRES16xFS17MAP** [comment]
Sorry about that we will look into it and send everyone an updated xml file today so you can unload.

**Comment by BROADACRES16xFS17MAP** [comment]
I have added a new map01.xml on our page. Instructions on how to replace is noted on there

**Comment by BROADACRES16xFS17MAP** [comment]
Please let us know how it goes

**Comment by SunkenL** [comment]
Seems that it didnt work for me when i replaced the new map01.xml in "maps folder"
![bild](https://user-images.githubusercontent.com/24603095/32449803-d774bcb0-c312-11e7-9b06-db472f16c516.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Make sure it replaced the file. It worked ok for others. Check time/date of the file.

**Comment by BROADACRES16xFS17MAP** [comment]
I've added a V2 appears millet was still missing off that one. Third time lucky.

**Comment by SunkenL** [comment]
Sorry for late answer. It works now but i dont get any dough for it :D
