### ISSUE TITLE
Change empty triggers with all pipes (BA edited )

### ISSUE THREAD

**Issue by Bundy-Bear** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#60]
Grain outlet doesn't line up

![son](https://user-images.githubusercontent.com/32672100/32428294-22ea7bf2-c319-11e7-8a94-870b1354a238.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Not video glitch its a setting in the map thats a bit off cheers will fix

**Comment by BROADACRES16xFS17MAP** [comment]
All tested and adjusted
