### ISSUE TITLE
SP Mission (Harvest) Spawn Point needs moving or rotating

### ISSUE THREAD

**Issue by s7davis** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#61]
Good afternoon all, I was doing a Harvest mission on field 3 i believe and when you accept the mission for harvesting the headers hitch hits the fence as it spawns in and throws the header around to where you can not hook up to it. I will post a pic to show what is going on.

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks is it all of them or one in particular. Photo would be great

**Comment by s7davis** [comment]
here are some pics of spawn points for missions. I think it is on all fields not that far in game so only have the starting fields right now so this is on Field 3

![mission spawn close to fence2](https://user-images.githubusercontent.com/33438678/32528246-de32d800-c3e6-11e7-8ad4-97e2140b1857.png)
![mission spawn close to fence](https://user-images.githubusercontent.com/33438678/32528247-de4b05ba-c3e6-11e7-9f50-bf70f5cdea12.png)

**Comment by BROADACRES16xFS17MAP** [comment]
Moved Hired Worker triggers inside field. Fixed
