### ISSUE TITLE
Painted Foilage Layer of Tree Leaves on Field 3

### ISSUE THREAD

**Issue by s7davis** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#62]
Good afternoon while doing a mission on field 3 noticed some painted foilage (Leaves) on field 3 around the following coordinates (7662, 560) area. This is on field 3 on the north side of the field.

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks do you have a picture with oda showing location please?

**Comment by s7davis** [comment]
This is at 7659 511 are the coords that I am at this time


![field 3 foilage](https://user-images.githubusercontent.com/33438678/32477344-3729ef4e-c332-11e7-99b9-5aedca83326f.png)
![field 3 with coords](https://user-images.githubusercontent.com/33438678/32477345-373e3094-c332-11e7-9993-6263dda7127b.png)

](url)

**Comment by BROADACRES16xFS17MAP** [comment]
#52 refers and fixed. Thanks for reporting though.
