### ISSUE TITLE
Milk not accepted at Krispy Kreme

### ISSUE THREAD

**Issue by Bundy-Bear** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#63]
![kk](https://user-images.githubusercontent.com/32672100/32492386-33181f2a-c40e-11e7-815d-ed1968e6e0f3.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
It wont. Need to convert it at the dairy and sell the Hmilk
