### ISSUE TITLE
Map doesn't load in

### ISSUE THREAD

**Issue by WinZ1992** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#64]
I tried every single recommendation. Tried every single resolution options. Deleted all other mods and maps. Still nothing, just waiting the map to load in.

[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1451754/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Which version do you have and were did you download. According to log your still loading other mods and courseplay is incorrectly added into your folder. Your maps arent zipped either which 
Is ok until you want to play multiplater. They are better.if they are zipped.

**Comment by Bundy-Bear** [comment]
Could this be an issue

Farming Simulator 17
  Version: 1.2.0.0 1.2RC6

**Comment by BROADACRES16xFS17MAP** [comment]
Could be Bundy Bear. Lot of changes since then. WinZ1992 maybe try update too. Looking at the error I am thinking you may have  a dodgy download. Try all these fixes and let us know.

**Comment by WinZ1992** [comment]
Hey guys.
So I'm here again. I've updated the game and removed all the mods etc.
Now I have a memory failure. "Bad allocation; out of memory."

Here's my new log. Can I do anything with it or I just have to admit that this mod is not for my PC?
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1457562/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
I would say pc may be a little low to run it sorry mate.
