### ISSUE TITLE
Warning Space Characters

### ISSUE THREAD

**Issue by s7davis** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#65]
Good afternoon their are a ton of space characters in the map I know this has nothing to do with the performance of the map just letting it be known. I was going thru the map01.i3d file in notepad++ and saw them. 

Also their is still a thumb.db somewhere in the map. Hard to tell where because I can not get the map to read moddesc.xml on our dedicated server for some reason. Maybe because we use verygames.net for our dedicated server and i think it only allows 1.7G upload but am not sure.

**Comment by BROADACRES16xFS17MAP** [comment]
Hi yes we are aware but they are from mods we i cluded in map. As you said it doesnt affect the performabce in server as we have tested thoroughly in server as well. If server only allows 1.7gb then it wint load map.
