### ISSUE TITLE
Toll Storage Depot

### ISSUE THREAD

**Issue by babylon5657** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#66]
Not sure if the Toll storage facility is designed to have these attributes or not, so i posted here and on FB page.

When i use Toll semi to deliver produce to the front of the building it registers on PDA as 4 times the amount i delivered, i.e 4k litres of tomatoes shows as 16k on PDA. When i go to unload at real i get the original 4k back in truck. I know i had seen somewhere on another map about issues with fruit types registering at 4 times the quantity on PDA.

The second issue and again it may be designed this way is that when you load from a loading bay at the rear of the building you dont get all the produce you have stored. Today i placed beer in storage and i got some from one bay and had to move to another bay to get the rest.

As i said this might be how the building is designed to work, just not sure.

Thanks

**Comment by babylon5657** [comment]
Cheers

**Comment by spectrum69** [comment]
he have reason with that 
i have same issue with all palets and product

**Comment by BROADACRES16xFS17MAP** [comment]
Okay need some clarification on this one as I have begun to test 👍 

For the second issue you were having:
1) Are you filling your product from the same trigger i.e. were you unload , you fill back up at same rear trigger? I've tested and it fills to 100% if using the same trigger.

**Comment by BROADACRES16xFS17MAP** [comment]
Okay so this is now fixed. We have decided to have one bay for loading unloading. If we had more than one in that close proximity it was recording more than what it should have plus giving the confusing loading values. 

With this fix it reads correctly in PDA as well as loading/unloading.
