### ISSUE TITLE
errors picking up beer at brewery

### ISSUE THREAD

**Issue by farmwrangler** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#68]
game locks up when loading beer. Alt-f4 to get out of game. log attached.
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1455792/log.txt)

**Comment by farmwrangler** [comment]
sorry. forgot. Using the toll food trailer.

**Comment by BROADACRES16xFS17MAP** [comment]
okay you have a lot of errors but appears you have Broad Acres in another Broad Acres folder?????

 =J:/FS2017/MAPS/Broad Acres/Broad_Acres/maps/scripts/PalettenSammler.lua (267) : getTranslatio

You have alot of mods trying to run out of the Broad Acres folder aswell which isnt right and will cause you issues.

**Comment by farmwrangler** [comment]
the broad_acres folder is just the map unzipped. I run all my maps unzipped. I've had twice as many mods in other maps, including corn belt 16x with no problems, and over 72 hours in your map with no problems. Except trying to load beer....  If you're going to blame errors like this on having too many mods, then I see no reason for me to continue to report any errors.

**Comment by BROADACRES16xFS17MAP** [comment]
No need to get angry just trying to eliminate errors as others havent reported same issue and i cant see what you are doing. Explain to me what you are doing and if you are picking them up from the plate whilst still being made.

**Comment by BROADACRES16xFS17MAP** [comment]
If you would like to explain in more detail I'm more than happy to help but I will close this topic for now.

**Comment by farmwrangler** [comment]
Once the pallet strip was full, and the pallet making process stopped, I backed up the food trailer to the strip and began loading pallets. Got half way through and the game froze. Tried 3 times in a row with same result. Seems like the fabrik script isn't allowing enough time to gather all the pallets before restarting?

**Comment by BROADACRES16xFS17MAP** [comment]
Ok thanks we will look into it and test.

**Comment by aussiegamer2017** [comment]
ok so i had this problem too, it come down 2 other flat bed trailers i had, i just un-ticked these two mods and it's all running fine

mods that where interfering: semi-bale 50000\6 (v1.0.0.1)
                                               flatbed trailer ual (v5.0.0.0)

so you will need to go through and work out what mods are causing the conflicted

**Comment by aussiegamer2017** [comment]
also forgot i have no errors in my log after doing this

**Comment by farmwrangler** [comment]
I tried the toll ual flatbed trailer and I couldn't get it to work. Couldn't select work position or choose pallet size, bales etc. Then I tried the non-toll fliegl ual flatbed trailer and it grabs the beer pallets just fine. So the mod conflict is probably in the toll trailers.

**Comment by BROADACRES16xFS17MAP** [comment]
Not meant to use the flat bed as the fiegel one isn't designed for beer. For beer pickup, use the toll curtain trailer instead.

**Comment by farmwrangler** [comment]
The curtain trailer freezing the game is what this issue is all about. Just to let you know, the non-toll fliegl ual flatbed trailer works, where the others don't.

**Comment by farmwrangler** [comment]
Here's a screenshot.
![fsscreen_2017_11_10_20_58_24](https://user-images.githubusercontent.com/33469940/32686464-1c363c80-c65a-11e7-867e-f37ee6bebd5e.png)

**Comment by BROADACRES16xFS17MAP** [comment]
We have tested and so have others including the one reporting it was a mod conflict. We do not get a freeze therefore something else is conflicting with the toll trailers on your pc. I cant help anymore as we have tested to make sure and have came to the same conclusion as post yesterday is that its other mods conflicting.

**Comment by spectrum69** [comment]
it is normal the freeze of the game it is due to the script of the trailer it causes this error on all the map known defs17 it is in slacker it is all
when i use this fridge trailer i take a fenwick or a clark
it's not the map or the trailer but the player who is the problem


tester map
