### ISSUE TITLE
Wool Pallet Production Area

### ISSUE THREAD

**Issue by babylon5657** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#69]
I am not sure again if this is a fault or if its how its meant to look. Instead of filling all available slots the pallets move to the spaces as shown in the picture below and then i get message saying "no more room"
![screenshot 4](https://user-images.githubusercontent.com/32924811/32609253-fc82a198-c556-11e7-9182-bf5d4a2a183a.png)

[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1457838/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Have you removed any before it did this? Try to remove all except one being made and let it start again

**Comment by ledge1978** [comment]
I had a similar problem in testing when using creator tools mod going at any speed greater than x120. This could be a mod issue

**Comment by babylon5657** [comment]
This is 2nd time it happened. I will retest with a vanilla version

I just looked after i removed a trailer load of wool and the spawn point was clear so i removed the last 2 pallets with a loader and wool has started to respawn. I dont use creators tool

**Comment by BROADACRES16xFS17MAP** [comment]
Let us know if it works, but yes the speed at 120x with pallets can be an issue

**Comment by babylon5657** [comment]
Just retested on a vanilla version and it worked as intended. Must be a mod conflict as the only time i fast forward at 120x is overnight.

Sorry to have not tested without mods before posting here

**Comment by BROADACRES16xFS17MAP** [comment]
All good glad you got it fixed.
