### ISSUE TITLE
lumber train unhooking

### ISSUE THREAD

**Issue by farmwrangler** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#71]
While making my second looksee by train video, I noticed that the lumber train unhooks from the locomotive when taking off from it's default place. It rehooks after moving forward a bit. Best seen in my video: https://youtu.be/OQrBHOo4SWk

Shows it in the very beginning and at the end of the video as I return to the default place. Also, I turned on the fps display a couple of minutes into the video. May be a good indicator which areas show a lag (none are real bad, but you might want to have a looksee).

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks yes it does. Already fixed for V2 :-)
