### ISSUE TITLE
selling straw  prices loose straw vs bales

### ISSUE THREAD

**Issue by cill2003** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#72]
Hi all, i have a question about selling straw. I've sold loose straw and i've sold bales of straw. The bales brought me next to nothing, while the loose straw ga gave me a lot more income. Is this intended or is this a bug. seems to me that bales should be worth more because it's a lot more work

**Comment by BROADACRES16xFS17MAP** [comment]
straw no halved in price - fixed
