### ISSUE TITLE
Can't sell vehicles at store

### ISSUE THREAD

**Issue by farmwrangler** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#73]
Has anyone else reported a problem with selling vehicles at the store? I can't seem to find the sweet spot. Hitting R just turns up a blank sell screen. Same with configuring vehicles, although the placeable vehicle config shack works.

**Comment by BROADACRES16xFS17MAP** [comment]
See trigger here. If ever in doubt hit F5 and it will glow the triggers for you.

![2017-11-11](https://user-images.githubusercontent.com/7673205/32685855-b5e1cf90-c6e9-11e7-9ef9-f49e96290084.png)
