### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by bigcountry1089** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#74]
ok took all the mods off and it started but also started with all mods but freezes up
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1464207/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
okay here are your issues

1) Error: Invalid mod name 'Broad Acres Package'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit (make sure that the package is unzipped, there are other zips in this zip. Just open it up and move the zip folders into the mods folder)

Removee these mods

Error: Failed to open xml file 'C:/Users/little/Documents/My Games/FarmingSimulator2017/mods/FS1760FTCutterPackUnzipMe_ModLandNet/modDesc.xml'.

Error: Failed to open xml file 'C:/Users/little/Documents/My Games/FarmingSimulator2017/mods/FS1760FTCutterPackUnzipMe_ModLandNet/modDesc.xml'.

Here is your major issue so remove and retry

Error: D3D11Texture::init: Creation of texture with checked formats failed 
  ..\..\..\src\base\3d\d3d11\D3D11Texture.cpp (531)Error: Can't load resource 'C:/Users/little/Documents/My Games/FarmingSimulator2017/mods/OKC_TR_FordLTL_v2_ModLandNet/store.dds'.
Error: Render device Error: Unknown.

**Comment by BROADACRES16xFS17MAP** [comment]
Please let me know if this resolves the issue so I can close it. If not please post another log with these issues resolved.

**Comment by BROADACRES16xFS17MAP** [comment]
Please post a new log.txt thanks.
