### ISSUE TITLE
freezes up

### ISSUE THREAD

**Issue by bigcountry1089** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#75]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1465119/log.txt)
after taking off the mods which were causing problems but still freezes up

**Comment by BROADACRES16xFS17MAP** [comment]
If you open the log you will see your mods are still being loaded. Did you start a fresh game? Take all mods out of the mods folder and place them in a new folder in desktop. Make sure broadacres.zip is taken out of the downloaded package zip and add it back into mods folder. Start new game and see how it goes.report back

**Comment by BROADACRES16xFS17MAP** [comment]
P.s. dont need ti start a new issue evertime hust reply to first one. Ill close this one. #74
