### ISSUE TITLE
Grain Not Unloading From Silo

### ISSUE THREAD

**Issue by BcoxTheHunter** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#76]
Don't know if this has been reported yet, but the SE farm silos (Near BGA) the load point into a trailer does not have a trigger at it. I used the dev tools, it seems like the trigger has got moved over the the unload point.

Screenshots:

![screen shot 11-13-17 at 05 51 pm 002](https://user-images.githubusercontent.com/33641206/32753582-6b097c8a-c89b-11e7-9f09-d2b58d0a6e0f.PNG)
(Shows the loading trigger into a trailer is missing from where it should be. Also shows my location the the map)

![screen shot 11-13-17 at 05 51 pm](https://user-images.githubusercontent.com/33641206/32753597-7dd64384-c89b-11e7-8c45-6d913d3a1d68.PNG)
(Shows what looks like the loading trigger over where the unload point into the silo is)

**Comment by BcoxTheHunter** [comment]
I have checked with a trailer, the load trigger is over with the trigger to empty into the silo. (Shown in second screenshot)

**Comment by BROADACRES16xFS17MAP** [comment]
Thanks mate, this has been fixed for v2. You can still fill from there but it's not in the right place.
