### ISSUE TITLE
Post all Suggestions/Compliments Here Only (Issues to be posted in general area)

### ISSUE THREAD

**Issue by BROADACRES16xFS17MAP** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#8]
**Broad Acres is built to what I would like to see in a map.  It's flat because we are mainly flat in Australia. Please dont post comments about adding hills etc. This area is more for posting suggestions for newer versions etc etc. Most of the posts here will not be replied to but will definitely be read and taken into consideration. Thanks.**

**Comment by aceman91** [comment]
Hi I see the pdf and mods are out to download but I can't see the link for the map?

**Comment by rwzippy** [comment]
Hi aceman. He map isn't out yet. The manual was released for people to read in over in preparation for the map release. 

The manual plays an important role in this map. It's highly recommended you have a read through before starting a game when it is released. 

Regards.

**Comment by spectrum69** [comment]
we can store the sugar cane, the sugar beet and the potato in the stock but not the other carrot onions and so it does not show up in the PDA
Can you change that
and or put a slider above the bulk stock to see the fill level
