### ISSUE TITLE
Tree seedlings disappear after saving.

### ISSUE THREAD

**Issue by Pumpuy71** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#80]
Tree seed bought from the shop and loaded on the trailer.

![03_01_the trailer laden with the tree seedlings saved game and left the game](https://user-images.githubusercontent.com/33676252/32815514-02927ccc-c9e7-11e7-983b-024000bf4fc0.jpg)

![03_02_shop](https://user-images.githubusercontent.com/33676252/32815543-31c2ae2c-c9e7-11e7-8c06-2e65e4badcd3.jpg)

Saved the game and left the game.

![03_03_game saved](https://user-images.githubusercontent.com/33676252/32815568-49f3bf7c-c9e7-11e7-9062-1d87b4b9cf0b.jpg)

Game reloaded to continue playing. and no more trees in the pallet.

![03_04_game restarted](https://user-images.githubusercontent.com/33676252/32815580-57278a20-c9e7-11e7-9fd3-a7b00c606d49.jpg)

![03_05_no more seedlings in the pallets](https://user-images.githubusercontent.com/33676252/32815591-61fd2ed2-c9e7-11e7-9b71-e9418611a6c3.jpg)

![03_06_saplings have reached the next level of growth](https://user-images.githubusercontent.com/33676252/32815615-74042338-c9e7-11e7-9379-6d2abb7659ee.jpg)

![03_07_because i have the offset and at the next growth stage man still can not recognize her](https://user-images.githubusercontent.com/33676252/32815630-8667ee7e-c9e7-11e7-9ac3-6bd568b534bb.jpg)

![03-08_also there was planted nothing can be seen at the next stage of growth](https://user-images.githubusercontent.com/33676252/32815640-92fff780-c9e7-11e7-9793-4c5f9447c4d9.jpg)

![03-09_before saving put everything then is good](https://user-images.githubusercontent.com/33676252/32815650-a3c1785a-c9e7-11e7-92c7-69bfeaba6924.jpg)

even at the next level of tree growth. you can not see anything.
before saving, put everything, then is good.

**Comment by BROADACRES16xFS17MAP** [comment]
Okay anything on a trailer will disapear after a saved game. It's a well known Giants issue and they haven't fixed it yet. Basically anything on a trailer take it off before an exit/save game as you will loose it. I can't say much more about this one as it's a GIANTS issue so just keep this in mind before you save and exit a game.
