### ISSUE TITLE
Woodchip storage?

### ISSUE THREAD

**Issue by Marcacous** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#87]
Perhaps if possible can you add wood chips to the PDA so you know how much you have in storage?  the storage/loading point at the forest sawmill

**Comment by BROADACRES16xFS17MAP** [comment]
Are you talking about the train traiker loading area? Pics are helpful.

**Comment by Marcacous** [comment]
yes. the place where you load woodchips into the train.

**Comment by BROADACRES16xFS17MAP** [comment]
This is a different trigger so wint shiw up on pda as its only a temp storage. The train triggers work by placing trailer or carriage underneath and when you want to fill it will show the screen and how much available.

**Comment by Marcacous** [comment]
Negative on that part. placing a train or a tipper under the spouts do not show how much is in there as it ONLY stores wood chips from what i have seen so is no option to tell you how much is stored.

**Comment by BROADACRES16xFS17MAP** [comment]
I see what you mean, i'll see what I can do on that part cheers.

**Comment by BROADACRES16xFS17MAP** [comment]
Digital displays now added to both outputs
