### ISSUE TITLE
Pig food maker

### ISSUE THREAD

**Issue by Marcacous** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#88]
giving wierd graphics displays. 
![screenshot_3](https://user-images.githubusercontent.com/33852475/33055934-2a6a534a-ce48-11e7-81a8-11d3b368120a.png)

was not there till everything was added to the pig food maker. 3 of us on the server at the time could all see it.

**Comment by BROADACRES16xFS17MAP** [comment]
Fixed for v2

**Comment by spectrum69** [comment]
![a](https://user-images.githubusercontent.com/25110957/33233925-6890dbb0-d21e-11e7-94ec-74da34aae6cf.jpg)
