### ISSUE TITLE
Trains lag

### ISSUE THREAD

**Issue by Marcacous** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#90]
on our MP server as soon as i start moving the train a few of our server members get alot of lag.
typical ms for one guy is around 30 and FPS of about 40. as soon as i move the train his ping jumps to 80+ and drops to around 9 FPS. Doesn't matter where he is on the map or what direction he is looking.
i don't seem to experience any issues on my end. there are a few players that get the same issues. 
If there is anything you need us to try or more stats we run devmode but no idea what kinda info in there may be usefull

**Comment by BROADACRES16xFS17MAP** [comment]
You will get some lag with trains. Depending on your system will depend on how much. We find once you get going the lag becomes better.
