### ISSUE TITLE
Kenworth Prime Mover

### ISSUE THREAD

**Issue by Stephen9999** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#91]
Minor issue but in running the Kenny in a road train the load make the Kenny uncontrollable as if the frontend is lifted, and speed is restrict to 30 Klms max. This does not make good game play.

Also looking forward to V2 and a descent cotton and sugarcane harvester. Anyone know of a good one. The sugarcane one from platinum version doesn't work well when towing a large trailer by the harvester or working beside it.  Cotton one I found does work well either.

Just to add the maps runs well, no lag experienced.
Thanks,

**Comment by BROADACRES16xFS17MAP** [comment]
Hi thanks for the post. Can you tell us what you were carrying and assuming 3 trailers of the TOLL ones? We need the info so we can test and change if required. Thanks.

Not much on the market for cotton and sugarcane. Give it time there will be some more.

**Comment by spectrum69** [comment]
what's truck The kenworth

**Comment by Stephen9999** [comment]
Yes, Toll truck Kenny and grain wagons (2) pic attached. Front was full of wheat back on e partial, around 20K.
[Kenny rig.pdf](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1497803/Kenny.rig.pdf)

**Comment by Stephen9999** [comment]
Sorry hut the wrong button.

**Comment by BROADACRES16xFS17MAP** [comment]
Spectrum can you test please?

**Comment by spectrum69** [comment]
of course

**Comment by spectrum69** [comment]
fix ready for V2 BA i send the new version
