### ISSUE TITLE
Proposal for the brewery

### ISSUE THREAD

**Issue by Pumpuy71** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#93]
To bring some more reality into the game I have a suggestion.

How about if you would add additional hops there.

To make beer you needed hops and barley, or for a 2 type of beer wheat and hops.
As well as by-product or waste product, compost soil where you can reuse at the Greenhouses.

**Comment by primal71** [comment]
actually Hops is not essential for beer, you need beer barley and yeast. hops is purely for different bitterness or flavors of beer, but it is most certainly not a requirement for beer

**Comment by Pumpuy71** [comment]
Yes, that's clear, hops is not a requirement and that's why I said it as a suggestion
