### ISSUE TITLE
Compat. issue with Straw Harvest Addon.

### ISSUE THREAD

**Issue by CameronW1** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#97]
Hey. There's an issue with running the map with the Straw Harvest addon (link: https://www.aerosoft.com/us/other-simulations/farming/2080/farming-simulator-17-add-on-straw-harvest?c=555)

The game will just crash to desktop and the only reason I say it's a compat issue is that other maps will load 100% fine and just not the addon and this map.

**Comment by BROADACRES16xFS17MAP** [comment]
Please attach your log after crash. Thanks. Just drag and drop it in a reply.

**Comment by CameronW1** [comment]
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1523744/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Try loading just the map and new addon. Your mixing station placaable is throwing errors. Theres no errors for map crashing so gotta be another mod conflicting with the new mod. My tester got the straw addon today so he will test also.

**Comment by BROADACRES16xFS17MAP** [comment]
Appears our map doesn't like this addon and not sure why. Not throwing any errors in the log so we'll have to look into it further or wait for an update from the mod once they work out there bugs that may conflict.

**Comment by CameronW1** [comment]
Still crashing with only the addon and map installed.
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1524147/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Yeah we are having the same issue so well have to look into it.

**Comment by Willykeen** [comment]
Creative mesh have a topic on their website about bugs. Straw harvest addon
doesnt work on 4x and 16x maps as there is a compat bug

On 3 Dec. 2017 7:50 am, "BROADACRES16xFS17MAP" <notifications@github.com>
wrote:

Yeah we are having the same issue so well have to look into it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/issues/97#issuecomment-348719191>,
or mute the thread

**Comment by BROADACRES16xFS17MAP** [comment]
Have you got a link WIllykeen? Ive tried to search for the forum but must of had a boys look

**Comment by CameronW1** [comment]
Addon works 100% in NW Texas map (4x) So I don't know what else to say. And that's with all my other mods too.

**Comment by BROADACRES16xFS17MAP** [comment]
We believe it's a conflict with chopped straw. Maps we have tested with this installed has crashed. We wont be changing anything to suit one mod as it's a hell of a lot of work for one mod. Hopefully the mod creator will come up with a fix.

**Comment by CameronW1** [comment]
I usually bale instead. But having options would be better. Bale counter mod has conflicts too.

**Comment by BROADACRES16xFS17MAP** [comment]
Please see our facebook page for a fix we have added this morning of the moddesc.xml. If your not on facebook please let me know.

**Comment by CameronW1** [comment]
Found it, changed the .xml and still crashed while loading...log: 
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1537038/log.txt)

**Comment by CameronW1** [comment]
RE-did the .xml and now just loop loading nonstop. 
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1537110/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Remove some mods. The placeable compost mod is also causing issues for others. Just try game and addob first then retest adding mods in.

**Comment by CameronW1** [comment]
OK, I got in, but I get 1fps...

**Comment by BROADACRES16xFS17MAP** [comment]
Get rid if all mods? Give me a new log

**Comment by BROADACRES16xFS17MAP** [comment]
New game?

**Comment by DOUGHBOY39** [comment]
Hello I don't have any questions yet
