### ISSUE TITLE
Pallet disappear

### ISSUE THREAD

**Issue by AllanAllansson** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#98]
Why does a pallet disappear every time you load.
Then you will find a pallet located in the fields.
I had a pallet in both fields 18 and 19 now.
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1531966/log.txt)

**Comment by BROADACRES16xFS17MAP** [comment]
Just need some more info like what you are using to load,were are you loading etc etc. Explain to me what you have done so we can get a better picture thanks. If using toll have you got latest update that doesnt accept pallets anymore.

**Comment by AllanAllansson** [comment]
I'm using the Fliegl trailer both the new version and the old one. When I load ex. 7 pallets then disappear 1 after a few seconds. Sometimes it has jumped back on the conveyor belt, but for the most part I do not see it.
It happens at TipTop Bakery, Hyne Timberg and at Greenhouses.

**Comment by BROADACRES16xFS17MAP** [comment]
Okay do me a favour and disable all your mods except for the map and the toll package the  retest.

**Comment by AllanAllansson** [comment]
Have now tested with just the map and toll package.
When I loaded 12 pallets on the bakery, 2 pieces disappeared after a few seconds.
attach log file.
[log.txt](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1536540/log.txt)

**Comment by AllanAllansson** [comment]
Yesterday I tested some other trailers, and they did not work any pallets that disappeared.
So it seems to be the Toll trailer that is the problem

**Comment by AllanAllansson** [comment]
Soory
I've tested some other trailers yesterday, and they worked perfectly, no pallets that disappeared.
So it seems to be the Toll trailer that is the problem

**Comment by BROADACRES16xFS17MAP** [comment]
Okay log looks fine. Are you trying to load two different pallets onto same trailer? You can only load ine variety. If not ill need to see it on a video so we can try and replicate it for testing. Cheers.

**Comment by AllanAllansson** [comment]
I have recorded a movie, but how do I get it in the comment field.
I can zip the file and send it as an email.

**Comment by AllanAllansson** [comment]
Here it comes

[test1.zip](https://github.com/BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map/files/1536991/test1.zip)

**Comment by BROADACRES16xFS17MAP** [comment]
Ill have a look tonight for you and test

**Comment by BROADACRES16xFS17MAP** [comment]
New version coming out tonight
