### ISSUE TITLE
V2 testing for testers only

### ISSUE THREAD

**Issue by BROADACRES16xFS17MAP** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#99]

**Comment by Cajunman45** [comment]
![447020_screenshots_20171223230226_1](https://user-images.githubusercontent.com/32685358/34324591-365eb37a-e83e-11e7-9331-530a6612e2a4.jpg)
Field 8 has Barr wire sticking out in field and blocking path of harvester .   Go in gate by shed and go str8 to first comer by back of shed 

![fixed-vs-broken-one-person-repair-solves-problem-others-fail-lifts-word-crushed-word-to-illustrate-power-41820015](https://user-images.githubusercontent.com/7673205/34328848-8c2f56b2-e93b-11e7-8abc-060b7943e53f.jpg)

**Comment by Cajunman45** [comment]
![447020_screenshots_20171223192355_1](https://user-images.githubusercontent.com/32685358/34324652-2fb8e66a-e840-11e7-8fe7-276e6cc337b4.jpg)
Field 14 NE gate has barr wire sticking out of it 

![fixed-vs-broken-one-person-repair-solves-problem-others-fail-lifts-word-crushed-word-to-illustrate-power-41820015](https://user-images.githubusercontent.com/7673205/34328851-967ee98e-e93b-11e7-90df-b42f34bb3b91.jpg)

**Comment by Cajunman45** [comment]
![image](https://user-images.githubusercontent.com/32685358/34366488-e7e3d934-ea61-11e7-8a01-e9c114b32190.png)

Gate opens in middle of road on  field 2 by the pigs SW gate 

![fixed-vs-broken-one-person-repair-solves-problem-others-fail-lifts-word-crushed-word-to-illustrate-power-41820015](https://user-images.githubusercontent.com/7673205/34371058-aa2663ce-eb19-11e7-90a7-5de23ac71ce8.jpg)

**Comment by BROADACRES16xFS17MAP** [comment]
Fixed floating vegetables piles in storage bays in each area.

**Comment by DOUGHBOY39** [comment]
Guys I'm just getting up and going I'm testing on everything that I can so don't give up

**Comment by BROADACRES16xFS17MAP** [comment]
All good its been slow due to holidays. Ive been away for last 3 days. We have a trailer/dolly release when i get home today.

**Comment by DOUGHBOY39** [comment]
Cool only things I have found wrong is the gate at field 2 beside the pigs opens into the road and the one right out of town that goes by fields 18 and 19 I think opens on to the train tracks that's it so  iv got pics of them just don't know how to put them on here

**Comment by BROADACRES16xFS17MAP** [comment]
Nice work just drag the pic into a reply box and they will upload. Then press comment button
